(require :asdf)
(push (truename (make-pathname :directory '(:relative :up))) asdf:*central-registry*)
(asdf:load-system :clvt)
(in-package :clvt)

(defun parse-json (path)
  (with-open-file (s path :direction :input)
    (let* ((len (file-length s)) (buf (make-string len)) (pos 0))
      (read-sequence buf s)
      (labels ((skip () (loop while (and (< pos len) (member (char buf pos) '(#\Space #\Tab #\Newline #\Return))) do (incf pos)))
               (rd () (skip) (when (>= pos len) (return-from rd nil))
                 (let ((c (char buf pos)))
                   (cond
                     ((char= c #\") (incf pos) (let ((st pos)) (loop while (and (< pos len) (char/= (char buf pos) #\")) do (when (char= (char buf pos) #\\) (incf pos)) (incf pos)) (prog1 (subseq buf st pos) (incf pos))))
                     ((char= c #\[) (incf pos) (skip) (let ((a nil)) (loop while (and (< pos len) (char/= (char buf pos) #\])) do (push (rd) a) (skip) (when (and (< pos len) (char= (char buf pos) #\,)) (incf pos) (skip))) (incf pos) (nreverse a)))
                     ((char= c #\{) (incf pos) (skip) (let ((h (make-hash-table :test 'equal))) (loop while (and (< pos len) (char/= (char buf pos) #\})) do (let ((k (rd))) (skip) (when (and (< pos len) (char= (char buf pos) #\:)) (incf pos)) (setf (gethash k h) (rd))) (skip) (when (and (< pos len) (char= (char buf pos) #\,)) (incf pos) (skip))) (incf pos) h))
                     ((or (char<= #\0 c #\9) (char= c #\-) (char= c #\+)) (let ((st pos)) (when (member c '(#\- #\+)) (incf pos)) (loop while (and (< pos len) (or (char<= #\0 (char buf pos) #\9) (char= (char buf pos) #\.) (member (char buf pos) '(#\e #\E #\d #\D #\- #\+)))) do (incf pos)) (let* ((s0 (subseq buf st pos)) (s1 (substitute #\e #\d (substitute #\e #\D s0)))) (if (or (find #\. s1) (find #\e s1) (find #\E s1)) (let ((*read-eval* nil)) (read-from-string s1)) (parse-integer s1)))))
                     ((and (< (+ pos 4) len) (string= (subseq buf pos (min len (+ pos 4))) "true")) (incf pos 4) t)
                     ((and (< (+ pos 5) len) (string= (subseq buf pos (min len (+ pos 5))) "false")) (incf pos 5) nil)
                     ((and (< (+ pos 4) len) (string= (subseq buf pos (min len (+ pos 4))) "null")) (incf pos 4) nil)
                     (t (error "JSON error at ~a: ~a" pos c))))))
        (rd)))))

(defvar *N* 0) (defvar *P* 0) (defvar *F* 0) (defvar *F-list* nil)
(defun approx (e a &optional (tol 1e-6))
  (cond ((and (numberp e) (numberp a)) (if (and (floatp e) (floatp a)) (< (abs (- e a)) (+ tol (* 0.001 (abs e)))) (eql e a)))
        ((and (listp e) (listp a)) (and (= (length e) (length a)) (every (lambda (x y) (approx x y tol)) e a)))
        (t (equal e a))))
(defun get-val (entry) (cond ((hash-table-p entry) (let ((t0 (gethash "t" entry))) (cond ((string= t0 "a") (gethash "v" entry)) ((string= t0 "i") (gethash "v" entry)) ((string= t0 "f") (gethash "v" entry)) ((string= t0 "l") (gethash "v" entry)) ((string= t0 "n") nil) (t entry)))) (t entry)))
(defun T! (name expected actual &optional (tol 1e-6))
  (incf *N*) (if (approx expected actual tol) (incf *P*) (progn (incf *F*) (push name *F-list*) (format t "  X ~a~%" name))))
(defun E (J key) (get-val (gethash key J)))
(defun summary ()
  (format t "~%=== Total: ~a | Pass: ~a | Fail: ~a ===~%" *N* *P* *F*)
  (when *F-list* (format t "Failed:~{~%  - ~a~}~%" (reverse *F-list*)))
  (zerop *F*))

(defun run ()
  (format t "~%=== clvt PARAMETRIC TESTS (3D+, multi-axis) ===~%")
  (let* ((J (parse-json "test/param_expected.json"))
         (m (vt-astype (vt-reshape (vt-arange 12 :dtype :int64) '(3 4)) :float64))
         (mi (vt-reshape (vt-arange 12 :dtype :int64) '(3 4)))
         (t3 (vt-astype (vt-reshape (vt-arange 24 :dtype :int64) '(2 3 4)) :float64))
         (ti (vt-reshape (vt-arange 24 :dtype :int64) '(2 3 4)))
         (t222 (vt-from-sequence '(((1.0 2.0) (3.0 4.0)) ((5.0 6.0) (7.0 8.0)))))
         (t222i (vt-from-sequence '(((1 2) (3 4)) ((5 6) (7 8))) :dtype :int64)))

    ;; --- Reduction 2D ---
    (T! "sum_2d_all" (E J "sum_2d_all") (vt-item (vt-sum m)) 1e-06)
    (T! "sum_2d_ax0" (E J "sum_2d_ax0") (vt-to-list (vt-sum m :axis 0)) 1e-06)
    (T! "sum_2d_ax1" (E J "sum_2d_ax1") (vt-to-list (vt-sum m :axis 1)) 1e-06)
    (T! "sum_2d_ax-1" (E J "sum_2d_ax_neg1") (vt-to-list (vt-sum m :axis -1)) 1e-06)
    (T! "sum_2d_kd0" (E J "sum_2d_ax0_kd") (vt-to-list (vt-sum m :axis 0 :keepdims t)) 1e-06)
    (T! "mean_2d_all" (E J "mean_2d_all") (vt-item (vt-mean m)) 1e-06)
    (T! "mean_2d_ax0" (E J "mean_2d_ax0") (vt-to-list (vt-mean m :axis 0)) 1e-06)
    (T! "mean_2d_ax1" (E J "mean_2d_ax1") (vt-to-list (vt-mean m :axis 1)) 1e-06)
    (T! "max_2d_all" (E J "amax_2d_all") (vt-item (vt-amax m)) 1e-06)
    (T! "max_2d_ax0" (E J "amax_2d_ax0") (vt-to-list (vt-amax m :axis 0)) 1e-06)
    (T! "min_2d_ax1" (E J "amin_2d_ax1") (vt-to-list (vt-amin m :axis 1)) 1e-06)
    (T! "argmax_2d_ax0" (E J "argmax_2d_ax0") (vt-to-list (vt-argmax m :axis 0)) 1e-06)
    (T! "argmax_2d_ax1" (E J "argmax_2d_ax1") (vt-to-list (vt-argmax m :axis 1)) 1e-06)
    (T! "argmin_2d_ax0" (E J "argmin_2d_ax0") (vt-to-list (vt-argmin m :axis 0)) 1e-06)
    (T! "argmin_2d_ax-1" (E J "argmin_2d_ax_neg1") (vt-to-list (vt-argmin m :axis -1)) 1e-06)
    (T! "std_2d_all" (E J "std_2d_all") (vt-item (vt-std m)) 1e-06)
    (T! "var_2d_all" (E J "var_2d_all") (vt-item (vt-var m)) 1e-06)
    (T! "cumsum_2d_ax0" (E J "cumsum_2d_ax0") (vt-to-list (vt-cumsum mi :axis 0)) 1e-06)
    (T! "cumsum_2d_ax1" (E J "cumsum_2d_ax1") (vt-to-list (vt-cumsum mi :axis 1)) 1e-06)
    (T! "cumprod_2d_ax0" (E J "cumprod_2d_ax0") (vt-to-list (vt-cumprod mi :axis 0)) 1e-06)
    (T! "median_2d_ax0" (E J "median_2d_ax0") (vt-to-list (vt-median m :axis 0)) 1e-06)
    (T! "median_2d_ax1" (E J "median_2d_ax1") (vt-to-list (vt-median m :axis 1)) 1e-06)
    (T! "ptp_2d_ax0" (E J "ptp_2d_ax0") (vt-to-list (vt-ptp m :axis 0)) 1e-06)
    (T! "ptp_2d_ax1" (E J "ptp_2d_ax1") (vt-to-list (vt-ptp m :axis 1)) 1e-06)
    (T! "sort_2d_ax0" (E J "sort_2d_ax0") (vt-to-list (vt-sort m :axis 0)) 1e-06)
    (T! "sort_2d_ax1" (E J "sort_2d_ax1") (vt-to-list (vt-sort m :axis 1)) 1e-06)
    (T! "argsort_2d_ax0" (E J "argsort_2d_ax0") (vt-to-list (vt-argsort m :axis 0)) 1e-06)
    (T! "argsort_2d_ax1" (E J "argsort_2d_ax1") (vt-to-list (vt-argsort m :axis 1)) 1e-06)
    (T! "diff_2d_ax0" (E J "diff_2d_ax0") (vt-to-list (vt-diff m :axis 0)) 1e-06)
    (T! "diff_2d_ax1" (E J "diff_2d_ax1") (vt-to-list (vt-diff m :axis 1)) 1e-06)

    ;; --- Reduction 3D ---
    (T! "sum_3d_all" (E J "sum_3d_all") (vt-item (vt-sum t3)) 1e-06)
    (T! "sum_3d_ax0" (E J "sum_3d_ax0") (vt-to-list (vt-sum t3 :axis 0)) 1e-06)
    (T! "sum_3d_ax1" (E J "sum_3d_ax1") (vt-to-list (vt-sum t3 :axis 1)) 1e-06)
    (T! "sum_3d_ax2" (E J "sum_3d_ax2") (vt-to-list (vt-sum t3 :axis 2)) 1e-06)
    (T! "sum_3d_ax-1" (E J "sum_3d_ax_neg1") (vt-to-list (vt-sum t3 :axis -1)) 1e-06)
    (T! "sum_3d_ax-2" (E J "sum_3d_ax_neg2") (vt-to-list (vt-sum t3 :axis -2)) 1e-06)
    (T! "sum_3d_ax01" (E J "sum_3d_ax01") (vt-to-list (vt-sum t3 :axis '(0 1))) 1e-06)
    (T! "sum_3d_ax12" (E J "sum_3d_ax12") (vt-to-list (vt-sum t3 :axis '(1 2))) 1e-06)
    (T! "sum_3d_kd0" (E J "sum_3d_ax0_kd") (vt-to-list (vt-sum t3 :axis 0 :keepdims t)) 1e-06)
    (T! "sum_3d_kd2" (E J "sum_3d_ax2_kd") (vt-to-list (vt-sum t3 :axis 2 :keepdims t)) 1e-06)
    (T! "mean_3d_all" (E J "mean_3d_all") (vt-item (vt-mean t3)) 1e-06)
    (T! "mean_3d_ax0" (E J "mean_3d_ax0") (vt-to-list (vt-mean t3 :axis 0)) 1e-06)
    (T! "mean_3d_ax1" (E J "mean_3d_ax1") (vt-to-list (vt-mean t3 :axis 1)) 1e-06)
    (T! "mean_3d_ax2" (E J "mean_3d_ax2") (vt-to-list (vt-mean t3 :axis 2)) 1e-06)
    (T! "mean_3d_ax-1" (E J "mean_3d_ax_neg1") (vt-to-list (vt-mean t3 :axis -1)) 1e-06)
    (T! "mean_3d_ax01" (E J "mean_3d_ax01") (vt-to-list (vt-mean t3 :axis '(0 1))) 1e-06)
    (T! "mean_3d_kd0" (E J "mean_3d_ax0_kd") (vt-to-list (vt-mean t3 :axis 0 :keepdims t)) 1e-06)
    (T! "max_3d_all" (E J "amax_3d_all") (vt-item (vt-amax t3)) 1e-06)
    (T! "max_3d_ax0" (E J "amax_3d_ax0") (vt-to-list (vt-amax t3 :axis 0)) 1e-06)
    (T! "max_3d_ax2" (E J "amax_3d_ax2") (vt-to-list (vt-amax t3 :axis 2)) 1e-06)
    (T! "min_3d_ax1" (E J "amin_3d_ax1") (vt-to-list (vt-amin t3 :axis 1)) 1e-06)
    (T! "argmax_3d_ax0" (E J "argmax_3d_ax0") (vt-to-list (vt-argmax t3 :axis 0)) 1e-06)
    (T! "argmax_3d_ax2" (E J "argmax_3d_ax2") (vt-to-list (vt-argmax t3 :axis 2)) 1e-06)
    (T! "argmin_3d_ax0" (E J "argmin_3d_ax0") (vt-to-list (vt-argmin t3 :axis 0)) 1e-06)
    (T! "argmin_3d_ax1" (E J "argmin_3d_ax1") (vt-to-list (vt-argmin t3 :axis 1)) 1e-06)
    (T! "std_3d_ax0" (E J "std_3d_ax0") (vt-to-list (vt-std t3 :axis 0)) 1e-06)
    (T! "var_3d_ax2" (E J "var_3d_ax2") (vt-to-list (vt-var t3 :axis 2)) 1e-06)
    (T! "cumsum_3d_ax0" (E J "cumsum_3d_ax0") (vt-to-list (vt-cumsum ti :axis 0)) 1e-06)
    (T! "cumsum_3d_ax1" (E J "cumsum_3d_ax1") (vt-to-list (vt-cumsum ti :axis 1)) 1e-06)
    (T! "cumsum_3d_ax2" (E J "cumsum_3d_ax2") (vt-to-list (vt-cumsum ti :axis 2)) 1e-06)
    (T! "cumprod_3d_ax2" (E J "cumprod_3d_ax2") (vt-to-list (vt-cumprod ti :axis 2)) 1e-06)
    (T! "median_3d_ax0" (E J "median_3d_ax0") (vt-to-list (vt-median t3 :axis 0)) 1e-06)
    (T! "median_3d_ax2" (E J "median_3d_ax2") (vt-to-list (vt-median t3 :axis 2)) 1e-06)
    (T! "ptp_3d_ax0" (E J "ptp_3d_ax0") (vt-to-list (vt-ptp t3 :axis 0)) 1e-06)
    (T! "ptp_3d_ax2" (E J "ptp_3d_ax2") (vt-to-list (vt-ptp t3 :axis 2)) 1e-06)
    (T! "sort_3d_ax0" (E J "sort_3d_ax0") (vt-to-list (vt-sort t3 :axis 0)) 1e-06)
    (T! "sort_3d_ax2" (E J "sort_3d_ax2") (vt-to-list (vt-sort t3 :axis 2)) 1e-06)
    (T! "argsort_3d_ax0" (E J "argsort_3d_ax0") (vt-to-list (vt-argsort t3 :axis 0)) 1e-06)
    (T! "argsort_3d_ax2" (E J "argsort_3d_ax2") (vt-to-list (vt-argsort t3 :axis 2)) 1e-06)
    (T! "diff_3d_ax0" (E J "diff_3d_ax0") (vt-to-list (vt-diff t3 :axis 0)) 1e-06)
    (T! "diff_3d_ax2" (E J "diff_3d_ax2") (vt-to-list (vt-diff t3 :axis 2)) 1e-06)
    (T! "maximum_3d" (E J "maximum_3d") (vt-to-list (vt-maximum t3 (vt-flip t3 :axis 0))) 1e-06)
    (T! "minimum_3d" (E J "minimum_3d") (vt-to-list (vt-minimum t3 (vt-flip t3 :axis 0))) 1e-06)

    ;; --- Percentile 2D+3D ---
    (T! "pct25_2d_ax0" (E J "pct25_2d_ax0") (vt-to-list (vt-percentile m 25 :axis 0)) 1e-06)
    (T! "pct25_2d_ax1" (E J "pct25_2d_ax1") (vt-to-list (vt-percentile m 25 :axis 1)) 1e-06)
    (T! "pct25_3d_ax0" (E J "pct25_3d_ax0") (vt-to-list (vt-percentile t3 25 :axis 0)) 1e-06)
    (T! "pct25_3d_ax2" (E J "pct25_3d_ax2") (vt-to-list (vt-percentile t3 25 :axis 2)) 1e-06)
    (T! "pct50_2d_ax0" (E J "pct50_2d_ax0") (vt-to-list (vt-percentile m 50 :axis 0)) 1e-06)
    (T! "pct50_2d_ax1" (E J "pct50_2d_ax1") (vt-to-list (vt-percentile m 50 :axis 1)) 1e-06)
    (T! "pct50_3d_ax0" (E J "pct50_3d_ax0") (vt-to-list (vt-percentile t3 50 :axis 0)) 1e-06)
    (T! "pct50_3d_ax2" (E J "pct50_3d_ax2") (vt-to-list (vt-percentile t3 50 :axis 2)) 1e-06)
    (T! "pct75_2d_ax0" (E J "pct75_2d_ax0") (vt-to-list (vt-percentile m 75 :axis 0)) 1e-06)
    (T! "pct75_2d_ax1" (E J "pct75_2d_ax1") (vt-to-list (vt-percentile m 75 :axis 1)) 1e-06)
    (T! "pct75_3d_ax0" (E J "pct75_3d_ax0") (vt-to-list (vt-percentile t3 75 :axis 0)) 1e-06)
    (T! "pct75_3d_ax2" (E J "pct75_3d_ax2") (vt-to-list (vt-percentile t3 75 :axis 2)) 1e-06)
    (T! "pct90_2d_ax0" (E J "pct90_2d_ax0") (vt-to-list (vt-percentile m 90 :axis 0)) 1e-06)
    (T! "pct90_2d_ax1" (E J "pct90_2d_ax1") (vt-to-list (vt-percentile m 90 :axis 1)) 1e-06)
    (T! "pct90_3d_ax0" (E J "pct90_3d_ax0") (vt-to-list (vt-percentile t3 90 :axis 0)) 1e-06)
    (T! "pct90_3d_ax2" (E J "pct90_3d_ax2") (vt-to-list (vt-percentile t3 90 :axis 2)) 1e-06)

    ;; --- Shape 3D ---
    (T! "trans_3d_021" (E J "trans_3d_021") (vt-to-list (vt-transpose t3 '(0 2 1))) 1e-06)
    (T! "trans_3d_102" (E J "trans_3d_102") (vt-to-list (vt-transpose t3 '(1 0 2))) 1e-06)
    (T! "trans_3d_210" (E J "trans_3d_210") (vt-to-list (vt-transpose t3 '(2 1 0))) 1e-06)
    (T! "squeeze_134" (E J "squeeze_3d_134") (vt-to-list (vt-squeeze (vt-reshape (vt-arange 12 :dtype :int64) '(1 3 4)))) 1e-06)
    (T! "squeeze_314" (E J "squeeze_3d_314") (vt-to-list (vt-squeeze (vt-reshape (vt-arange 12 :dtype :int64) '(3 1 4)))) 1e-06)
    (T! "squeeze_341" (E J "squeeze_3d_341") (vt-to-list (vt-squeeze (vt-reshape (vt-arange 12 :dtype :int64) '(3 4 1)))) 1e-06)
    (T! "expand_3d_ax0" (E J "expand_3d_ax0_shape") (vt-shape (vt-expand-dims t3 0)) 1e-06)
    (T! "expand_3d_ax2" (E J "expand_3d_ax2_shape") (vt-shape (vt-expand-dims t3 2)) 1e-06)
    (T! "expand_3d_ax3" (E J "expand_3d_ax3_shape") (vt-shape (vt-expand-dims t3 3)) 1e-06)
    (T! "concat_3d_ax0" (E J "concat_3d_ax0") (vt-to-list (vt-concatenate 0 t3 (vt-+ t3 100.0))) 1e-06)
    (T! "flip_3d_ax0" (E J "flip_3d_ax0") (vt-to-list (vt-flip t3 :axis 0)) 1e-06)
    (T! "flip_3d_ax1" (E J "flip_3d_ax1") (vt-to-list (vt-flip t3 :axis 1)) 1e-06)
    (T! "flip_3d_ax2" (E J "flip_3d_ax2") (vt-to-list (vt-flip t3 :axis 2)) 1e-06)
    (T! "roll_3d_ax0" (E J "roll_3d_ax0") (vt-to-list (vt-roll ti 1 :axis 0)) 1e-06)
    (T! "roll_3d_ax2" (E J "roll_3d_ax2") (vt-to-list (vt-roll ti 1 :axis 2)) 1e-06)
    (T! "triu_3d" (E J "triu_3d") (vt-to-list (vt-triu t3)) 1e-06)
    (T! "tril_3d" (E J "tril_3d") (vt-to-list (vt-tril t3)) 1e-06)
    (T! "swapaxes_3d_01" (E J "swapaxes_3d_01") (vt-to-list (vt-swapaxes t3 0 1)) 1e-06)
    (T! "swapaxes_3d_02" (E J "swapaxes_3d_02") (vt-to-list (vt-swapaxes t3 0 2)) 1e-06)
    (T! "swapaxes_3d_12" (E J "swapaxes_3d_12") (vt-to-list (vt-swapaxes t3 1 2)) 1e-06)
    (T! "narrow_3d_ax0" (E J "narrow_3d_ax0") (vt-to-list (vt-narrow t3 0 0 1)) 1e-06)
    (T! "narrow_3d_ax1" (E J "narrow_3d_ax1") (vt-to-list (vt-narrow t3 1 1 3)) 1e-06)
    (T! "narrow_3d_ax2" (E J "narrow_3d_ax2") (vt-to-list (vt-narrow t3 2 1 3)) 1e-06)
    (T! "tile_3d_121" (E J "tile_3d_121") (vt-to-list (vt-tile t222i '(1 2 1))) 1e-06)
    (T! "tile_3d_212" (E J "tile_3d_212") (vt-to-list (vt-tile t222i '(2 1 2))) 1e-06)
    (T! "repeat_3d_ax0" (E J "repeat_3d_ax0") (vt-to-list (vt-repeat t222i 2 :axis 0)) 1e-06)
    (T! "repeat_3d_ax2" (E J "repeat_3d_ax2") (vt-to-list (vt-repeat t222i 2 :axis 2)) 1e-06)
    (T! "pad_3d_const" (E J "pad_3d_const") (vt-to-list (vt-pad t222 1 :mode :constant :constant-values 0)) 1e-06)
    (T! "pad_3d_edge" (E J "pad_3d_edge") (vt-to-list (vt-pad t222 1 :mode :edge)) 1e-06)
    (T! "broadcast_1x3x4" (E J "broadcast_1x3x4_to_2x3x4") (vt-to-list (vt-broadcast-to (vt-reshape (vt-arange 12 :dtype :int64) '(1 3 4)) '(2 3 4))) 1e-06)

    ;; --- Arithmetic 3D ---
    (T! "add_3d_scalar" (E J "add_3d_scalar") (vt-to-list (vt-+ t3 10.0)) 1e-06)
    (T! "mul_3d_scalar" (E J "mul_3d_scalar") (vt-to-list (vt-* t3 2.0)) 1e-06)
    (T! "add_3d_3d" (E J "add_3d_3d") (vt-to-list (vt-+ t3 t3)) 1e-06)
    (T! "mul_3d_3d" (E J "mul_3d_3d") (vt-to-list (vt-* t3 t3)) 1e-06)
    (T! "abs_3d" (E J "abs_3d") (vt-to-list (vt-abs (vt-- t3 12.0))) 1e-06)
    (T! "square_3d" (E J "square_3d") (vt-to-list (vt-square t3)) 1e-06)
    (T! "sqrt_3d" (E J "sqrt_3d") (vt-to-list (vt-sqrt (vt-abs t3))) 1e-06)
    (T! "exp_3d" (E J "exp_3d") (vt-to-list (vt-exp (vt-scale t3 0.1))) 1e-06)
    (T! "log_3d" (E J "log_3d") (vt-to-list (vt-log (vt-+ (vt-abs t3) 1.0))) 1e-06)
    (T! "clip_3d" (E J "clip_3d") (vt-to-list (vt-clip t3 5.0 15.0)) 1e-06)

    ;; --- Trig 3D ---
    (T! "sin_3d" (E J "sin_3d") (vt-to-list (vt-sin (vt-scale t3 0.1))) 1e-06)
    (T! "cos_3d" (E J "cos_3d") (vt-to-list (vt-cos (vt-scale t3 0.1))) 1e-06)
    (T! "tanh_3d" (E J "tanh_3d") (vt-to-list (vt-tanh (vt-scale (vt-- t3 12.0) 0.1))) 1e-06)

    ;; --- Comparison 3D ---
    (T! "lt_3d" (E J "lt_3d") (vt-to-list (vt-< t3 12.0)) 1e-06)
    (T! "gt_3d" (E J "gt_3d") (vt-to-list (vt-> t3 12.0)) 1e-06)
    (T! "isfinite_3d" (E J "isfinite_3d") (vt-to-list (vt-isfinite t3)) 1e-06)
    (T! "all_3d_ax0" (E J "all_3d_ax0") (vt-to-list (vt-all (vt-> t3 0.0) :axis 0)) 1e-06)
    (T! "any_3d_ax2" (E J "any_3d_ax2") (vt-to-list (vt-any (vt-> t3 10.0) :axis 2)) 1e-06)

    ;; --- einsum advanced ---
    (T! "einsum_trace_2d" (E J "einsum_trace_2d") (vt-item (vt-einsum "ii->" (vt-reshape (vt-arange 4 :dtype :int64) '(2 2)))) 1e-06)
    (T! "einsum_3d_reduce" (E J "einsum_3d_reduce") (vt-to-list (vt-einsum "ijk->i" t3)) 1e-06)
    (T! "einsum_3d_ax2" (E J "einsum_3d_reduce_ax2") (vt-to-list (vt-einsum "ijk->ij" t3)) 1e-06)

    ;; --- Where/Nonzero 3D ---
    (T! "where_3d" (E J "where_3d") (vt-to-list (vt-where (vt-> t3 12.0) t3 (vt-zeros '(2 3 4)))) 1e-06)

    ;; --- nan 3D ---

    ;; --- Activation 3D ---
    (T! "sigmoid_3d" (E J "sigmoid_3d") (vt-to-list (vt-sigmoid t3)) 1e-06)
    (T! "relu_3d" (E J "relu_3d") (vt-to-list (vt-relu (vt-- t3 12.0))) 1e-06)

    ;; --- Diagonal 3D (fixed bug) ---
    (T! "diag_3d" (E J "diag_3d") (vt-to-list (vt-diagonal t3)))
    (T! "convolve_valid" (E J "convolve_valid") (vt-to-list (vt-convolve (vt-from-sequence '(1.0 2.0 3.0 4.0 5.0)) (vt-from-sequence '(1.0 0.0 -1.0)) :mode :valid)))
    (T! "convolve_full" (E J "convolve_full") (vt-to-list (vt-convolve (vt-from-sequence '(1.0 2.0 3.0 4.0 5.0)) (vt-from-sequence '(1.0 0.0 -1.0)) :mode :full)))

    ;; --- Eigenvalue decomposition (fixed bug) ---
    (let ((a (vt-from-sequence '((4.0 2.0 1.0) (2.0 5.0 3.0) (1.0 3.0 6.0)) :dtype :float64)))
      (multiple-value-bind (vals vecs) (vt-eig a :max-iter 500)
        (T! "eig_3x3_vals" (E J "eig_3x3_vals") (vt-to-list vals))))

    ;; --- Stack 3D (was skipped) ---
    (T! "stack_3d_ax0" (E J "stack_3d_ax0") (vt-shape (vt-stack 0 t3 (vt-+ t3 100.0))))
    (T! "stack_3d_ax3" (E J "stack_3d_ax3") (vt-shape (vt-stack 3 t3 (vt-+ t3 100.0))))

    ;; --- Split 3D (was skipped) ---
    (let ((parts (vt-split t3 2 :axis 0)))
      (T! "split_3d_ax0" (E J "split_3d_ax0") (mapcar #'vt-to-list parts)))
    (let ((parts (vt-split t3 2 :axis 2)))
      (T! "split_3d_ax2" (E J "split_3d_ax2") (mapcar #'vt-to-list parts)))

    ;; --- Floor/Round 3D (was skipped) ---
    (T! "floor_3d" (E J "floor_3d") (vt-to-list (vt-floor (vt-scale t3 0.7))) 1.0)
    (T! "round_3d" (E J "round_3d") (vt-to-list (vt-round (vt-scale t3 0.7))) 1.0)

    ;; --- Diagonal 3D (PyTorch convention) ---
    (T! "diag_3d_pytorch" (E J "diag_3d_pytorch") (vt-to-list (vt-diagonal t3)))

    ;; --- Convolve ---
    (T! "convolve_valid" (E J "convolve_valid") (vt-to-list (vt-convolve (vt-from-sequence '(1.0 2.0 3.0 4.0 5.0)) (vt-from-sequence '(1.0 0.0 -1.0)) :mode :valid)))
    )
  (summary))

(run)
