;;;; indexing.lisp — 索引、切片、选择

(in-package :clvt)

(defun vt-ref (vt &rest indices)
  "获取指定位置元素（支持负索引，带边界检查）。"
  (declare (optimize (speed 3) (safety 0)))
  (let* ((shape (vt-shape vt))
         (rank (length shape)))
    (when (some #'zerop shape) (error "cannot index into an empty tensor"))
    (unless (= (length indices) rank)
      (error "索引数量 ~a 与维度数 ~a 不匹配" (length indices) rank))
    (let ((data (vt-data vt)) (ptr (vt-offset vt)))
      (loop for idx in indices
	    for dim in shape
	    for stride in (vt-strides vt)
            do (let ((i (if (minusp idx) (+ idx dim) idx)))
                 (unless (and (>= i 0) (< i dim))
                   (error "索引 ~a 越界（轴大小 ~a）" idx dim))
                 (incf ptr (* i stride))))
      (macrolet ((ref (lt)
		   `(aref (the (simple-array ,lt (*)) data) ptr)))
        (cond ((equal (array-element-type data) 'double-float) (ref double-float))
              ((equal (array-element-type data) 'single-float) (ref single-float))
              ((equal (array-element-type data) '(signed-byte 64)) (ref (signed-byte 64)))
              ((equal (array-element-type data) '(signed-byte 32)) (ref (signed-byte 32)))
              (t (aref data ptr)))))))

(defun (setf vt-ref) (value vt &rest indices)
  "设置指定位置元素（支持负索引，带边界检查）。"
  (declare (optimize (speed 3) (safety 0)))
  (let* ((shape (vt-shape vt))
         (rank (length shape)))
    (when (some #'zerop shape) (error "cannot index into an empty tensor"))
    (unless (= (length indices) rank)
      (error "索引数量 ~a 与维度数 ~a 不匹配" (length indices) rank))
    (let ((data (vt-data vt)) (ptr (vt-offset vt)))
      (loop for idx in indices
	    for dim in shape
	    for stride in (vt-strides vt)
            do (let ((i (if (minusp idx) (+ idx dim) idx)))
                 (unless (and (>= i 0) (< i dim))
                   (error "索引 ~a 越界（轴大小 ~a）" idx dim))
                 (incf ptr (* i stride))))
      (let ((cval (coerce value (vt-element-type vt))))
        (macrolet ((set-ref (lt)
		     `(setf (aref (the (simple-array ,lt (*)) data) ptr) cval)))
          (cond ((equal (array-element-type data) 'double-float) (set-ref double-float))
                ((equal (array-element-type data) 'single-float) (set-ref single-float))
                ((equal (array-element-type data) '(signed-byte 64)) (set-ref (signed-byte 64)))
                ((equal (array-element-type data) '(signed-byte 32)) (set-ref (signed-byte 32)))
                (t (setf (aref data ptr) cval))))))))

(defun vt-item (x)
  "0 维张量解包为原生数字，其余原样返回。"
  (if (and (vt-p x) (null (vt-shape x))) (vt-ref x) x))

(defun vt-slice (vt &rest specs)
  "统一切片接口。每个 spec 为列表：
   (:all)/(t) 全选；(:newa) 新轴；(:elli) 省略号；
   (idx) 整数索引降维；(start end &optional step) 范围切片。"
  (declare (optimize (speed 3)))
  (let* ((old-shape   (vt-shape vt))
         (old-strides (vt-strides vt))
         (old-offset  (vt-offset vt))
         (old-rank    (length old-shape))
         (osv  (coerce old-shape   'simple-vector))
         (ostv (coerce old-strides 'simple-vector))
         (n-specs (length specs)))
    (let ((elli-seen nil)
          (num-new 0)
          (num-index 0))
      (declare (fixnum num-new num-index))
      (dolist (s specs)
        (when (consp s)
          (let ((k (car s)))
            (cond ((eq k :elli)
                   (when elli-seen
                     (error "vt-slice: :elli 只能出现一次"))
                   (setf elli-seen t))
                  ((eq k :newa) (incf num-new))
                  ((and (null (cdr s)) (integerp k)) (incf num-index))))))
      (let* ((consuming (- n-specs (if elli-seen 1 0) num-new))
             (out-rank (- (+ old-rank num-new) num-index)))
        (when (> consuming old-rank)
          (error "vt-slice: 索引数 ~d 超过秩 ~d" consuming old-rank))
        (let ((needed (- old-rank consuming)))
          (declare (fixnum needed))
          (let ((new-shape   (make-array out-rank :element-type 'fixnum))
                (new-strides (make-array out-rank :element-type 'fixnum)))
            (declare (type (simple-array fixnum (*)) new-shape new-strides))
            (let ((out-i 0)
                  (axis-idx 0)
                  (cur-offset old-offset))
              (declare (fixnum out-i axis-idx cur-offset))
              (labels
                  ((emit-n-all (n)
                     (declare (fixnum n))
                     (dotimes (j n)
                       (declare (ignorable j))
                       (when (>= axis-idx old-rank)
                         (error "vt-slice: axis ~d 越界" axis-idx))
                       (setf (aref new-shape   out-i) (the fixnum (svref osv  axis-idx)))
                       (setf (aref new-strides out-i) (the fixnum (svref ostv axis-idx)))
                       (incf out-i)
                       (incf axis-idx)))
                   (emit-newa ()
                     (setf (aref new-shape   out-i) 1
                           (aref new-strides out-i) 0)
                     (incf out-i))
                   (emit-all-axis ()
                     (when (>= axis-idx old-rank)
                       (error "vt-slice: axis ~d 越界" axis-idx))
                     (setf (aref new-shape   out-i) (the fixnum (svref osv  axis-idx)))
                     (setf (aref new-strides out-i) (the fixnum (svref ostv axis-idx)))
                     (incf out-i)
                     (incf axis-idx))
                   (emit-index (idx)
                     (when (>= axis-idx old-rank)
                       (error "vt-slice: axis ~d 越界" axis-idx))
                     (let ((dim    (the fixnum (svref osv  axis-idx)))
                           (stride (the fixnum (svref ostv axis-idx)))
                           (i      (the fixnum idx)))
                       (declare (fixnum dim stride i))
                       (when (minusp i) (incf i dim))
                       (unless (and (>= i 0) (< i dim))
                         (error "vt-slice: index ~d out of bounds for axis ~d (size ~d)"
                                idx axis-idx dim))
                       (incf cur-offset (the fixnum (* i stride)))
                       (incf axis-idx)))
                   (emit-range (start end step)
                     (declare (type (or null fixnum) start end)
                              (fixnum step))
                     (when (>= axis-idx old-rank)
                       (error "vt-slice: axis ~d 越界" axis-idx))
                     (when (= 0 step)
                       (error "vt-slice: slice step cannot be zero"))
                     (let ((dim    (the fixnum (svref osv  axis-idx)))
                           (stride (the fixnum (svref ostv axis-idx))))
                       (declare (fixnum dim stride))
                       (let ((s (when start
                                  (let ((s (the fixnum (truncate start))))
                                    (if (minusp s) (the fixnum (+ s dim)) s))))
                             (e (when end
                                  (let ((e (the fixnum (truncate end))))
                                    (if (minusp e) (the fixnum (+ e dim)) e)))))
                         (declare (type (or null fixnum) s e))
                         (if (plusp step)
                             (let* ((s* (if s (max 0 (min s dim)) 0))
                                    (e* (if e (max 0 (min e dim)) dim))
                                    (len (if (> e* s*)
                                             (ceiling (- e* s*) step)
                                             0)))
                               (declare (fixnum s* e* len))
                               (incf cur-offset (the fixnum (* s* stride)))
                               (setf (aref new-shape   out-i) len
                                     (aref new-strides out-i) (* stride step)))
                             (let* ((s* (if s (max -1 (min s (1- dim))) (the fixnum (1- dim))))
                                    (e* (if e (max -1 (min e (1- dim))) -1))
                                    (len (if (> s* e*)
                                             (ceiling (- s* e*) (- step))
                                             0)))
                               (declare (fixnum s* e* len))
                               (incf cur-offset (the fixnum (* s* stride)))
                               (setf (aref new-shape   out-i) len
                                     (aref new-strides out-i) (* stride step))))
                         (incf out-i)
                         (incf axis-idx)))))
                (dolist (spec specs)
                  (if (not (consp spec))
                      (error "vt-slice: invalid slice spec ~a" spec)
                      (let ((k (car spec)))
                        (cond
                          ((and (eq k :elli) (null (cdr spec)))
                           (emit-n-all needed))
                          ((and (eq k :newa) (null (cdr spec))) (emit-newa))
                          ((and (eq k :all)  (null (cdr spec))) (emit-all-axis))
                          ((and (eq k t)     (null (cdr spec))) (emit-all-axis))
                          ((and (null (cdr spec)) (integerp k))
                           (emit-index k))
                          ((<= 2 (length spec) 3)
                           (emit-range (first spec) (second spec)
                                       (if (cddr spec) (third spec) 1)))
                          (t (error "vt-slice: invalid slice spec ~a" spec))))))
                (unless elli-seen
                  (emit-n-all (- old-rank axis-idx))))
              (unless (= out-i out-rank)
                (error "vt-slice: 内部错误 out-i=~d out-rank=~d" out-i out-rank))
              (%make-vt :data (vt-data vt)
                        :shape   (coerce new-shape   'list)
                        :strides (coerce new-strides 'list)
                        :offset  cur-offset
                        :dtype   (vt-dtype vt)))))))))

(defun (setf vt-slice) (value vt &rest specs)
  "设置切片区域值（value 可为标量或张量，支持广播）。"
  (let ((target-view (apply #'vt-slice vt specs)))
    (if (null (vt-shape target-view))
        (let ((scalar (cond ((numberp value) value)
                            ((vt-p value)
                             (if (null (vt-shape value))
				 (aref (vt-data value) (vt-offset value))
                                 (error "cannot assign tensor ~a to scalar slice"
					(vt-shape value))))
                            (t (error "invalid value ~a for scalar slice" value)))))
          (setf (vt-ref target-view) scalar))
        (vt-copy-into target-view value))))

(defun vt-where (condition x y &key out dtype)
  "三元条件选择（对标 torch.where / np.where(cond, x, y)）。"
  (setf condition (ensure-vt condition)
	x (ensure-vt x)
	y (ensure-vt y))
  (let* ((target-shape (vt-broadcast-shapes
			(vt-shape condition)
                        (vt-broadcast-shapes (vt-shape x) (vt-shape y))))
         (promoted (vt-promote-type (vt-dtype x) (vt-dtype y)))
         (final-dtype (cond ((and out dtype)
                             (unless (eq (vt-dtype out) dtype)
                               (error "vt-where: :out (~a) 与 :dtype (~a) 冲突"
				      (vt-dtype out) dtype))
                             (vt-dtype out))
                            (out (vt-dtype out))
                            (dtype dtype)
                            (t promoted)))
         (result (if out (progn (unless (equal (vt-shape out) target-shape)
                                  (error "vt-where: :out 形状不匹配"))
                               out)
                     (vt-zeros target-shape :dtype final-dtype))))
    (vt-map (lambda (c a b) (if (/= c 0) a b))
            condition x y :out result :dtype final-dtype)))

(defun vt-argwhere (condition &key (dtype :int64))
  "返回非零元素坐标，形状 (n, rank)。"
  (let* ((final (if (member dtype '(:int32 :int64)) dtype :int64))
         (lisp-type (if (eq final :int32) '(signed-byte 32) '(signed-byte 64)))
         (shape (vt-shape condition))
	 (rank (length shape))
         (data (vt-data condition))
	 (offset (vt-offset condition))
         (shape-vec (coerce shape 'simple-vector))
         (strides-vec (coerce (vt-strides condition) 'simple-vector))
         (result (make-array 64 :element-type '(signed-byte 64)
				:fill-pointer 0 :adjustable t))
         (coord (make-array rank :element-type '(signed-byte 64))))
    (labels ((recurse (depth ptr)
               (if (= depth rank)
                   (when (/= (aref data ptr) 0)
                     (if (zerop rank)
                         (vector-push-extend 0 result)
                         (loop for c across coord
			       do (vector-push-extend c result))))
                   (let ((dim (svref shape-vec depth))
			 (stride (svref strides-vec depth)))
                     (loop for i from 0 below dim do
                       (setf (aref coord depth) i)
                       (recurse (1+ depth) (+ ptr (* i stride))))))))
      (recurse 0 offset))
    (let* ((total (length result))
           (count (if (zerop rank) total (floor total rank))))
      (cond ((zerop count)
	     (vt-zeros (list 0 rank) :dtype final))
            ((> rank 0)
             (let ((final-data (make-array total :element-type lisp-type)))
               (loop for i from 0 below total for idx across result
                     do (setf (aref final-data i) idx))
               (%make-vt :data final-data :shape (list count rank) :strides (list rank 1)
                         :offset 0 :dtype final)))
            (t (%make-vt :data (make-array 0 :element-type lisp-type)
                         :shape (list count 0) :strides '(0 1) :offset 0 :dtype final))))))

(defun vt-nonzero (condition)
  "返回非零元素在各维度的索引列表（对标 torch.nonzero(as_tuple=true)）。
   rank = 0（标量）时，返回 (list (vt-zeros '(0) :dtype :int64))：
   - 长度 1 的列表，表示「存在非零元素」；
   - 内含形状 (0) 的空索引张量，表示「0 维张量没有可索引的维度」。
   这样既能区分「非零标量」与「零标量」（后者走 (zerop num) 分支返回 nil），
   又与 NumPy 对 0 维输入的 (array([0]),) 语义在「有个元素被选中」这一点上对齐。"
  (let* ((condition (if (numberp condition)
                        (ensure-vt condition)
                        condition))
         (shape (vt-shape condition))
         (rank (length shape))
         (data (vt-data condition))
         (offset (vt-offset condition))
         (in-strides (vt-strides condition))
         (logic-strides (vt-compute-strides shape))
         (nz '()))
    (labels ((recurse (depth logic-idx ptr)
               (if (= depth rank)
                   (unless (zerop (aref data ptr)) (push logic-idx nz))
                   (let ((dim (nth depth shape))
                         (in-stride (nth depth in-strides))
                         (logic-stride (nth depth logic-strides)))
                     (loop for i from 0 below dim do
                       (recurse (1+ depth)
                                (+ logic-idx (* i logic-stride))
                                (+ ptr (* i in-stride))))))))
      (recurse 0 0 offset))
    (setf nz (nreverse nz))
    (let ((num (length nz)))
      (cond
        ((zerop rank)
         (list (vt-zeros '(0) :dtype :int64)))
        ((zerop num)
         (loop repeat rank collect (vt-zeros '(0) :dtype :int64)))
        (t
         (let ((arrays (loop repeat rank
                             collect (make-array num
                                                 :element-type '(signed-byte 64)))))
           (loop for flat in nz for i from 0 do
             (let ((rem flat))
               (loop for d from 0 below rank
                     for stride in logic-strides do
                 (let ((coord (floor rem stride)))
                   (setf (aref (nth d arrays) i) coord)
                   (decf rem (* coord stride))))))
           (loop for arr in arrays
                 collect (%make-vt :data arr
                                   :shape (list num)
                                   :strides '(1)
                                   :offset 0
                                   :dtype :int64))))))))

(defun vt-take (tensor indices &key axis)
  "按索引取值（axis 为 nil 时展平取值，否则沿指定轴 gather）。"
  (labels ((fixnum-1d (vt)
             (let* ((len (vt-size vt))
		    (arr (make-array len :element-type '(signed-byte 64))))
               (dotimes (i len)
                 (setf (aref arr i)
                       (let ((v (aref (vt-data vt) i)))
                         (if (floatp v) (truncate v) v))))
               arr)))
    (if (null axis)
        (let* ((idx-vt (ensure-vt indices))
	       (flat (vt-ravel tensor))
	       (size (vt-size flat)))
          (if (null (vt-shape idx-vt))
              (let* ((raw (truncate (aref (vt-data idx-vt) 0)))
                     (idx (if (minusp raw) (+ raw size) raw)))
                (unless (<= 0 idx (1- size)) (error "索引 ~d 越界" idx))
                (make-vt nil (aref (vt-data flat) idx) :dtype (vt-dtype tensor)))
              (let* ((idx-shape (vt-shape idx-vt))
		     (out (vt-zeros idx-shape :dtype (vt-dtype tensor)))
                     (idx-arr (fixnum-1d idx-vt))
		     (idx-len (vt-size idx-vt))
                     (flat-data (vt-data flat))
		     (out-data (vt-data out)))
                (dotimes (i idx-len)
                  (let* ((raw (aref idx-arr i))
                         (idx (if (minusp raw) (+ raw size) raw)))
                    (unless (<= 0 idx (1- size)) (error "索引 ~d 越界" idx))
                    (setf (aref out-data i) (aref flat-data idx))))
                out)))
        (let* ((shape (vt-shape tensor))
	       (rank (length shape))
               (ax (vt-normalize-axis axis rank))
	       (ax-dim (nth ax shape))
               (idx-vt (ensure-vt indices))
	       (idx-shape (vt-shape idx-vt))
               (idx-rank (length idx-shape))
	       (idx-size (vt-size idx-vt))
               (out-shape (append (subseq shape 0 ax)
				  idx-shape (subseq shape (1+ ax))))
               (out (vt-zeros out-shape :dtype (vt-dtype tensor)))
               (idx-arr (fixnum-1d idx-vt))
               (idx-strides (vt-compute-strides idx-shape))
               (in-strides (vt-strides tensor))
	       (out-strides (vt-strides out))
               (in-off (vt-offset tensor))
	       (in-data (vt-data tensor)) (out-data (vt-data out)))
          (labels ((recurse (depth in-ptr out-ptr)
                     (if (= depth rank)
                         (setf (aref out-data out-ptr) (aref in-data in-ptr))
                         (if (= depth ax)
                             (walk-idx 0 0 in-ptr out-ptr)
                             (let ((dim (nth depth shape))
                                   (in-str (nth depth in-strides))
                                   (out-str (nth (if (< depth ax)
						     depth
						     (+ depth idx-rank -1))
						 out-strides)))
                               (dotimes (i dim)
                                 (recurse (1+ depth)
					  (+ in-ptr (* i in-str))
					  (+ out-ptr (* i out-str))))))))
                   (walk-idx (d idx-off in-ptr out-base)
                     (if (= d idx-rank)
                         (let* ((raw (aref idx-arr idx-off))
                                (idx (if (minusp raw) (+ raw ax-dim) raw)))
                           (unless (<= 0 idx (1- ax-dim))
                             (error "索引 ~d 越界，轴 ~d 大小 ~d" raw ax ax-dim))
                           (recurse (1+ ax) (+ in-ptr (* idx (nth ax in-strides))) out-base))
                         (let ((dim (nth d idx-shape))
			       (idx-str (nth d idx-strides))
                               (out-str (nth (+ ax d) out-strides)))
                           (dotimes (i dim)
                             (walk-idx (1+ d) (+ idx-off (* i idx-str)) in-ptr
                                       (+ out-base (* i out-str))))))))
            (recurse 0 in-off 0))
          out))))

(defun vt-put (tensor indices values &key (mode :raise))
  "按展平索引就地写入 values。"
  (let* ((total (vt-size tensor))
         (idx-list (if (numberp indices) (list (round indices))
                       (let ((flat (vt-flatten (ensure-vt indices))))
                         (loop for i below (vt-size flat)
			       collect (truncate (aref (vt-data flat) i))))))
         (val-list (cond ((numberp values) (list values))
                         ((or (listp values) (arrayp values))
			  (vt-flatten-sequence values))
                         ((vt-p values)
			  (let ((flat (vt-flatten (ensure-vt values))))
                            (loop for i below (vt-size flat)
				  collect (aref (vt-data flat) i))))))
         (n-values (length val-list)) (shape (vt-shape tensor))
         (strides (vt-strides tensor)) (offset (vt-offset tensor)) (data (vt-data tensor)))
    (loop for raw in idx-list for vi from 0
          for val = (nth (mod vi n-values) val-list)
          do (let ((idx raw))
               (when (and (minusp idx) (>= idx (- total))) (incf idx total))
               (cond ((and (>= idx 0) (< idx total)) nil)
                     ((eq mode :clip) (setq idx (max 0 (min idx (1- total)))))
                     ((eq mode :wrap) (setq idx (mod idx total)))
                     (t (error "索引 ~d 超出范围 [0, ~d)" raw total)))
               (let ((rem idx) (phys offset))
                 (loop for dim in (reverse shape)
		       for stride in (reverse strides)
                       do (multiple-value-bind (q r) (floor rem dim)
                            (incf phys (* r stride)) (setf rem q)))
                 (setf (aref data phys) (vt-cast val (vt-dtype tensor))))))
    tensor))

(defun vt-choose (choices indices &key (mode :raise))
  "根据索引数组从多个数组中选择值。对标 numpy.choose。
   choices : 候选张量列表，长度为 n。
   indices : 整数索引张量。
   mode    : 越界索引的处理方式，对标 np.choose 的 mode 参数：
             :raise (默认) — 负数或 >= n 都报错；
             :wrap         — 索引按 n 取模（-1 -> n-1）；
             :clip         — 索引裁剪到 [0, n-1]（-1 -> 0）。
   广播规则（与 NumPy 一致）：
     indices 与所有 choices 一起参与广播，输出形状为
       broadcast(indices.shape, choices[0].shape, choices[1].shape, ...)
   输出 dtype 为所有 choices 的提升类型。
   示例：
     (vt-choose (list c0 c1) idx)
       c0 = ((1 2) (3 4)), c1 = ((10 20) (30 40)), idx = ((1 0) (1 1))
       => shape (2 2), 值 ((10 2) (30 40))
     (vt-choose (list c0 c1) idx)   ; idx = ((0) (1)) shape (2,1)
       => shape (2 2), 值 ((1 2) (30 40))   ; 与 NumPy 一致"

  (let ((n (length choices)))
    (when (zerop n)
      (error "vt-choose: choices 不能为空"))

    (let* ((idx-vt      (ensure-vt indices))
           (choice-vts  (mapcar #'ensure-vt choices))
           (final-shape (reduce #'vt-broadcast-shapes
                                (cons (vt-shape idx-vt)
                                      (mapcar #'vt-shape choice-vts))))
           (idx-b       (vt-contiguous (vt-broadcast-to idx-vt final-shape)))
           (flat-choices
             (mapcar (lambda (c)
                       (vt-contiguous (vt-broadcast-to c final-shape)))
                     choice-vts))
           (final-size  (vt-shape-to-size final-shape))
           (idx-data    (vt-data idx-b))
           (idx-off     (vt-offset idx-b))
           (result-type (apply #'vt-promote-type
                               (mapcar #'vt-dtype flat-choices)))
           (result-data (make-array final-size
                                    :element-type
                                    (vt-dtype->lisp-type result-type))))
      (loop for i from 0 below final-size
            for raw = (truncate (aref idx-data (+ idx-off i)))
            for idx = (ecase mode
                        (:raise raw)
                        (:wrap  (mod raw n))
                        (:clip  (max 0 (min (1- n) raw))))
            do (when (or (< idx 0) (>= idx n))
                 (error "vt-choose: 索引 ~a 越界 (choices 数量 ~a)" raw n))
               (let* ((cv (nth idx flat-choices))
                      (cd (vt-data cv))
                      (co (vt-offset cv)))
                 (setf (aref result-data i)
                       (vt-cast (aref cd (+ co i)) result-type))))
      (%make-vt :data result-data
                :shape final-shape
                :strides (vt-compute-strides final-shape)
                :offset 0
                :dtype result-type))))

(defun vt-select (condlist choicelist &key (default 0))
  "根据多个条件从多个数组中选择。
   result = default
   for i from n-1 downto 0:
       result = vt-where(cond_i, choice_i, result)
   支持广播和非连续视图。"
  (let ((n (length condlist)))
    (unless (= n (length choicelist))
      (error "condlist and choicelist must have same length"))
    (when (zerop n)
      (error "condlist and choicelist cannot be empty"))

    (let* ((broadcast-shape (apply #'vt-broadcast-shapes
                                   (append (mapcar #'vt-shape condlist)
                                           (mapcar #'vt-shape choicelist))))
           ;; 默认值类型：整数按 int64，浮点按 float64（足够安全）
           (default-dtype (if (integerp default) :int64 :float64))
           ;; 所有可能值（choicelist + 默认值）的类型提升
           (result-dtype (apply #'vt-promote-type
                                (append (mapcar #'vt-dtype choicelist)
                                        (list default-dtype))))
           (result (vt-full broadcast-shape default :dtype result-dtype)))
      (loop for i from (1- n) downto 0
            for cond = (nth i condlist)
            for choice = (nth i choicelist)
            do (setf result (vt-where cond choice result)))
      result)))

(defun vt-extract (condition tensor)
  "根据条件提取元素。"
  (let* ((flat-cond (vt-flatten condition))
	 (flat-data (vt-flatten tensor))
         (cond-data (vt-data flat-cond))
	 (tensor-data (vt-data flat-data))
         (size (vt-size flat-data)) (result '()))
    (loop for i from 0 below size
          when (/= (aref cond-data i) 0)
            do (push (aref tensor-data i) result))
    (vt-from-sequence (nreverse result) :dtype (vt-dtype tensor))))

(defun vt-searchsorted (tensor values &key (side :left))
  "在有序数组中查找插入点。"
  (let* ((flat (vt-flatten tensor))
	 (data (vt-data flat))
	 (size (vt-size flat))
         (val-vt (ensure-vt values))
	 (v-flat (vt-flatten val-vt))
         (v-data (vt-data v-flat))
	 (v-size (vt-size v-flat))
         (result (make-array v-size :element-type '(signed-byte 64))))
    (loop for i from 0 below v-size for val = (aref v-data i)
          do (let ((lo 0) (hi size))
               (loop while (< lo hi) do
                 (let ((mid (ash (+ lo hi) -1)))
                   (if (if (eq side :right)
			   (> (aref data mid) val)
			   (>= (aref data mid) val))
                       (setf hi mid) (setf lo (1+ lo)))))
               (setf (aref result i) lo)))
    (%make-vt :data result :shape (list v-size) :strides '(1)
	      :offset 0 :dtype :int64)))

(defun vt-bincount (x &key (minlength 0))
  "统计非负整数出现次数。"
  (let* ((flat (vt-flatten x))
         (maxval (if (zerop (vt-size flat)) -1 (vt-item (vt-amax flat))))
         (size (max (1+ maxval) minlength))
         (result (make-array size :element-type '(signed-byte 64) :initial-element 0)))
    (vt-do-each (ptr val flat)
      (declare (ignore ptr))
      (let ((idx (truncate val)))
        (when (or (minusp idx) (>= idx size)) (error "vt-bincount: 索引 ~a 越界" idx))
        (incf (aref result idx))))
    (%make-vt :data result :shape (list size) :strides '(1)
	      :offset 0 :dtype :int64)))

(defun vt-digitize (x bins &key (right nil))
  "返回输入值在 bins 中的索引。"
  (let* ((flat-x (vt-flatten x)) (flat-bins (vt-flatten bins))
         (bin-data (vt-data flat-bins)) (nbins (vt-size flat-bins))
         (result (make-array (vt-size flat-x) :element-type '(signed-byte 64))))
    (vt-do-each (ptr val flat-x)
      (setf (aref result ptr)
            (loop for i from 0 below nbins
                  until (if right
			    (<= val (aref bin-data i))
			    (< val (aref bin-data i)))
                  finally (return i))))
    (%make-vt :data result :shape (vt-shape flat-x) :strides '(1)
	      :offset 0 :dtype :int64)))
