;;;; join.lisp — 连接、堆叠、追加、插入、删除

(in-package :clvt)

(defun vt-concatenate (axis &rest vts)
  "沿指定轴连接数组。"
  (when (null vts) (error "vt-concatenate 至少需要一个张量"))
  (let* ((shapes (mapcar #'vt-shape vts))
         (rank (length (car shapes)))
         (ax (vt-normalize-axis axis rank)))
    (loop for shape in shapes for i from 0
          do (unless (= (length shape) rank) (error "张量 ~a 秩不匹配" i))
             (loop for d in shape for j from 0
                   unless (or (= j ax) (= d (nth j (car shapes))))
                     do (error "形状不匹配")))
    (let* ((new-shape (copy-list (car shapes)))
           (total (reduce #'+ (mapcar (lambda (s) (nth ax s)) shapes)))
           (result-type (apply #'vt-promote-type (mapcar #'vt-dtype vts))))
      (setf (nth ax new-shape) total)
      (let ((result (vt-zeros new-shape :dtype result-type)) (cur 0))
        (dolist (vt vts)
          (let* ((axis-size (nth ax (vt-shape vt)))
                 (slice-args (loop for i below rank
                                   append (if (= i ax)
                                              (list (list cur (+ cur axis-size)))
                                              (list '(:all))))))
            (setf (apply #'vt-slice result slice-args) (vt-astype vt result-type))
            (incf cur axis-size)))
        result))))

(defun vt-concat (axis &rest vts)
  (apply #'vt-concatenate axis vts))

(defun vt-stack (axis &rest vts)
  "沿新轴堆叠。"
  (when (null vts) (error "vt-stack 至少需要一个张量"))
  (let ((base-shape (vt-shape (car vts))))
    (loop for vt in vts
          unless (equal (vt-shape vt) base-shape)
            do (error "张量形状不匹配"))
    (apply #'vt-concatenate axis (mapcar (lambda (vt) (vt-expand-dims vt axis)) vts))))

(defun vt-vstack (&rest vts) (apply #'vt-concatenate 0 vts))

(defun vt-hstack (&rest vts)
  (if (= (length (vt-shape (car vts))) 1)
      (apply #'vt-concatenate 0 vts)
      (apply #'vt-concatenate 1 vts)))

(defun vt-dstack (&rest vts)
  (when (null vts) (error "vt-dstack 至少需要一个张量"))
  (let ((expanded (mapcar (lambda (vt)
                            (let ((rank (length (vt-shape vt))))
                              (cond ((= rank 1) (vt-reshape vt (append (vt-shape vt) '(1 1))))
                                    ((= rank 2) (vt-reshape vt (append (vt-shape vt) '(1))))
                                    (t vt))))
                          vts)))
    (apply #'vt-concatenate 2 expanded)))

(defun vt-append (arr values &key (axis nil))
  "将 values 追加到 arr 末尾。"
  (let ((arr-vt (ensure-vt arr)) (val-vt (ensure-vt values)))
    (if (null axis)
        (vt-concatenate 0 (vt-flatten arr-vt) (vt-flatten val-vt))
        (let* ((rank (length (vt-shape arr-vt)))
               (ax (vt-normalize-axis axis rank)))
          (unless (= (length (vt-shape arr-vt)) (length (vt-shape val-vt)))
            (error "vt-append: 维度不匹配"))
          (loop for i below rank
                unless (or (= i ax) (= (nth i (vt-shape arr-vt)) (nth i (vt-shape val-vt))))
                  do (error "vt-append: 轴 ~a 形状不匹配" i))
          (vt-concatenate ax arr-vt val-vt)))))

(defun vt-insert (arr obj values &key (axis nil))
  "对标 numpy.insert 插入值。"
  (let* ((arr-vt (ensure-vt arr))
         (values-vt (ensure-vt values :dtype (vt-dtype arr-vt))))
    (if (null axis)
        (let* ((flat (vt-flatten arr-vt)) (flat-val (vt-flatten values-vt))
               (val-size (vt-size flat-val)))
          (if (integerp obj)
              (let* ((size (vt-size flat))
                     (pos (if (minusp obj) (+ size obj) obj)))
                (when (or (< pos 0) (> pos size)) (error "索引 ~a 越界" obj))
                (if (zerop val-size) flat
                    (let ((left (if (> pos 0) (vt-slice flat (list 0 pos)) (vt-zeros '(0) :dtype (vt-dtype flat))))
                          (right (if (< pos size) (vt-slice flat (list pos size)) (vt-zeros '(0) :dtype (vt-dtype flat)))))
                      (vt-concatenate 0 left flat-val right))))
              (let ((num (length obj)))
                (unless (or (= val-size num) (= val-size 1))
                  (error "flat mode: values 大小 ~a ≠ 索引数 ~a" val-size num))
                (let ((pairs (stable-sort
                              (if (= val-size 1)
                                  (loop for idx in obj collect (cons idx flat-val))
                                  (loop for idx in obj for i from 0 below val-size
                                        collect (cons idx (vt-narrow flat-val 0 i (1+ i)))))
                              #'> :key #'car)))
                  (loop with result = flat
                        for (raw-pos . val) in pairs
                        for size = (vt-size result)
                        for pos = (if (minusp raw-pos) (+ size raw-pos) raw-pos)
                        do (when (or (< pos 0) (> pos size)) (error "索引 ~a 越界" raw-pos))
                           (let ((left (if (> pos 0) (vt-slice result (list 0 pos)) (vt-zeros '(0) :dtype (vt-dtype result))))
                                 (right (if (< pos size) (vt-slice result (list pos size)) (vt-zeros '(0) :dtype (vt-dtype result)))))
                             (setf result (vt-concatenate 0 left val right)))
                        finally (return result))))))
        (let* ((shape (vt-shape arr-vt)) (rank (length shape))
               (ax (vt-normalize-axis axis rank))
               (ax-size (nth ax shape))
               (obj-list (if (listp obj) obj (list obj)))
               (num (length obj-list))
               (target-shape (loop for i below rank collect (if (= i ax) num (nth i shape))))
               (values-vt (if (null (vt-shape values-vt))
                              (vt-full target-shape (vt-ref values-vt) :dtype (vt-dtype values-vt))
                              values-vt))
               (values-reshaped (vt-reshape values-vt target-shape))
               (arr-slices (loop for i from 0 below ax-size collect (vt-narrow arr-vt ax i (1+ i))))
               (value-blocks (if (= num 1)
                                 (list values-reshaped)
                                 (loop for i from 0 below num collect (vt-narrow values-reshaped ax i (1+ i)))))
               (pairs (stable-sort (loop for pos in obj-list for b in value-blocks collect (cons pos b))
                                   #'> :key #'car)))
          (loop with slices = (copy-list arr-slices)
                for (raw-pos . block) in pairs
                for size = (length slices)
                for pos = (if (minusp raw-pos) (+ size raw-pos) raw-pos)
                do (when (or (< pos 0) (> pos size)) (error "索引 ~a 越界" raw-pos))
                   (setf slices (append (subseq slices 0 pos) (list block) (subseq slices pos)))
                finally (return (apply #'vt-concatenate ax slices)))))))

(defun vt-delete (arr obj &key (axis nil))
  "对标 numpy.delete 删除元素。"
  (let* ((tensor (ensure-vt arr)) (sh (vt-shape tensor)) (rank (length sh))
         (dtype (vt-dtype tensor)))
    (labels ((norm-idx (idx dim)
               (let ((n (if (minusp idx) (+ idx dim) idx)))
                 (unless (<= 0 n (1- dim)) (error "索引 ~d 越界（轴大小 ~d）" idx dim))
                 n))
             (norm-end (idx dim)
               (let ((n (if (minusp idx) (+ idx dim) idx)))
                 (unless (<= 0 n dim) (error "切片端点 ~d 越界（轴大小 ~d）" idx dim))
                 n))
             (keep (obj dim)
               (let ((del (make-hash-table :test 'eql)))
                 (flet ((add (i) (setf (gethash i del) t)))
                   (cond ((integerp obj) (add (norm-idx obj dim)))
                         ((and (listp obj) (eq (first obj) :slice))
                          (destructuring-bind (_ s e) obj
                            (declare (ignore _))
                            (let ((ss (norm-end s dim)) (ee (norm-end e dim)))
                              (loop for i from ss below ee do (add i)))))
                         ((listp obj) (dolist (idx obj) (add (norm-idx idx dim))))
                         (t (error "无效 obj 类型 ~a" obj))))
                 (loop for i from 0 below dim unless (gethash i del) collect i))))
      (if (null axis)
          (let* ((flat (vt-ravel tensor)) (k (keep obj (vt-size flat))))
            (if k (vt-take flat (vt-from-sequence k :dtype :int64))
                (vt-zeros '(0) :dtype dtype)))
          (let* ((ax (vt-normalize-axis axis rank)) (dim (nth ax sh))
                 (k (keep obj dim)))
            (if k
                (apply #'vt-concatenate ax (loop for i in k collect (vt-narrow tensor ax i (1+ i))))
                (let ((ns (copy-list sh)))
                  (setf (nth ax ns) 0)
                  (vt-zeros ns :dtype dtype))))))))
