;;;; reduce-stats.lisp — 归约、统计、排序、nan 感知统计、信号类函数

(in-package :clvt)

(defun vt-unravel-index (offset shape strides)
  "将物理偏移还原为逻辑坐标列表。"
  (loop with rem = offset for dim in shape for stride in strides
        collect (multiple-value-bind (idx r) (floor rem stride) (setf rem r) idx)))

(defun vt-sum (tensor &key axis keepdims dtype out)
  (let ((et (array-element-type (vt-data tensor))))
    (nth-value 0 (vt-reduce tensor axis (get-reduction-identity :sum et)
                            (lambda (acc val) (values (+ acc val) nil))
                            :out out :dtype dtype :keepdims keepdims))))

(defun vt-amax (tensor &key axis keepdims dtype out)
  (let ((et (array-element-type (vt-data tensor))))
    (nth-value 0 (vt-reduce tensor axis (get-reduction-identity :max et)
                            (lambda (acc val)
                              (cond ((vt-float-nan-p val) (if (vt-float-nan-p acc) (values acc nil) (values val t)))
                                    ((vt-float-nan-p acc) (values acc nil))
                                    (t (if (> val acc) (values val t) (values acc nil)))))
                            :out out :dtype dtype :keepdims keepdims))))

(defun vt-amin (tensor &key axis keepdims dtype out)
  (let ((et (array-element-type (vt-data tensor))))
    (nth-value 0 (vt-reduce tensor axis (get-reduction-identity :min et)
                            (lambda (acc val)
                              (cond ((vt-float-nan-p val) (if (vt-float-nan-p acc) (values acc nil) (values val t)))
                                    ((vt-float-nan-p acc) (values acc nil))
                                    (t (if (< val acc) (values val t) (values acc nil)))))
                            :out out :dtype dtype :keepdims keepdims))))

(defun vt-argmax (tensor &key axis out)
  (let ((et (array-element-type (vt-data tensor))))
    (nth-value 1 (vt-reduce tensor axis (get-reduction-identity :max et)
                            (lambda (acc val)
                              (cond ((vt-float-nan-p val) (if (vt-float-nan-p acc) (values acc nil) (values val t)))
                                    ((vt-float-nan-p acc) (values acc nil))
                                    (t (if (> val acc) (values val t) (values acc nil)))))
                            :out out :return-arg t))))

(defun vt-argmin (tensor &key axis out)
  (let ((et (array-element-type (vt-data tensor))))
    (nth-value 1 (vt-reduce tensor axis (get-reduction-identity :min et)
                            (lambda (acc val)
                              (cond ((vt-float-nan-p val) (if (vt-float-nan-p acc) (values acc nil) (values val t)))
                                    ((vt-float-nan-p acc) (values acc nil))
                                    (t (if (< val acc) (values val t) (values acc nil)))))
                            :out out :return-arg t))))

(defun vt-prod (tensor &key axis keepdims dtype out)
  (nth-value 0 (vt-reduce tensor axis 1
                          (lambda (acc val) (values (* acc val) nil))
                          :out out :dtype dtype :keepdims keepdims)))

(defun vt-all (condition &key axis keepdims)
  (nth-value 0 (vt-reduce condition axis 1
                          (lambda (acc val)
                            (values (if (and (/= acc 0) (/= val 0)) 1 0) nil))
                          :dtype :int32 :keepdims keepdims)))

(defun vt-any (condition &key axis keepdims)
  (nth-value 0 (vt-reduce condition axis 0
                          (lambda (acc val)
                            (values (if (or (/= acc 0) (/= val 0)) 1 0) nil))
                          :dtype :int32 :keepdims keepdims)))

(defun vt-isclose (t1 t2 &key (rtol 1e-5) (atol 1e-8) out)
  (vt-map (lambda (a b)
            (cond ((or (vt-float-nan-p a) (vt-float-nan-p b)) 0.0d0)
                  ((or (vt-float-inf-p a) (vt-float-inf-p b)) (if (= a b) 1.0d0 0.0d0))
                  (t (if (<= (abs (- a b)) (+ atol (* rtol (max (abs a) (abs b))))) 1.0d0 0.0d0))))
          t1 t2 :dtype :float64 :out out))

(defun vt-allclose (t1 t2 &key (rtol 1e-5) (atol 1e-8))
  (= (vt-item (vt-all (vt-isclose t1 t2 :rtol rtol :atol atol))) 1.0d0))

(defun vt-isfinite (vt &key out)
  (vt-map (lambda (x) (if (and (not (vt-float-nan-p x)) (not (vt-float-inf-p x))) 1.0d0 0.0d0))
          vt :dtype :float64 :out out))

(defun vt-isinf (vt &key out)
  (vt-map (lambda (x) (if (vt-float-inf-p x) 1.0d0 0.0d0)) vt :dtype :float64 :out out))

(defun vt-isnan (vt &key out)
  (vt-map (lambda (x) (if (vt-float-nan-p x) 1.0d0 0.0d0)) vt :dtype :float64 :out out))

;;; ------------------------------------------------------------------
;;; 均值 / 方差 / 标准差
;;; ------------------------------------------------------------------

(defun %get-axes-count (axis rank shape)
  (let* ((axes (vt-normalize-axes axis rank))
         (count (if axes (reduce #'* (mapcar (lambda (a) (nth a shape)) axes) :initial-value 1)
                    (reduce #'* shape :initial-value 1))))
    (values axes count)))

(defun vt-average (tensor weights &key axis keepdims dtype out)
  (let ((a-shape (vt-shape tensor)) (w-shape (vt-shape weights))
        (eff weights))
    (cond (axis (let* ((rank (length a-shape)) (ax (vt-normalize-axis axis rank))
                       (ax-size (nth ax a-shape)))
                  (unless (and (= (length w-shape) 1) (= (first w-shape) ax-size))
                    (error "1D weights expected when axis is specified"))
                  (setf eff (vt-reshape weights (loop for i below rank collect (if (= i ax) ax-size 1))))))
          (t (unless (equal w-shape a-shape)
               (error "weights must have same shape as a when axis is nil"))))
    (let* ((prod (vt-map #'* tensor eff))
           (weighted-sum (vt-sum prod :axis axis :keepdims keepdims))
           (sum-weights (vt-item (vt-sum weights)))
           (in-dtype (vt-dtype weighted-sum))
           (need-promote (member in-dtype '(:int32 :int64 :int16 :int8 :uint8 :uint16)))
           (exec-dtype (cond ((and out dtype (not (eq (vt-dtype out) dtype)))
                              (error "vt-average: :out 与 :dtype 冲突"))
                             (out (vt-dtype out)) (dtype dtype)
                             (need-promote :float64) (t in-dtype)))
           (nan-val (vt-get-nan exec-dtype))
           (scalar-divisor (coerce sum-weights (if (eq exec-dtype :float32) 'single-float 'double-float)))
           (map-dtype (cond (out nil) (dtype dtype) (need-promote :float64) (t nil))))
      (cond ((vt-float-nan-p sum-weights)
             (if out (progn (vt-map (lambda (x) (declare (ignore x)) nan-val) weighted-sum :out out :dtype dtype) out)
                 (vt-full (vt-shape weighted-sum) nan-val :dtype exec-dtype)))
            ((zerop sum-weights) (error "Weights sum to zero"))
            (t (vt-map (lambda (s) (/ s scalar-divisor)) weighted-sum :dtype map-dtype :out out))))))

(defun vt-mean (tensor &key axis keepdims dtype out)
  (let* ((shape (vt-shape tensor)) (rank (length shape)))
    (multiple-value-bind (axes count) (%get-axes-count axis rank shape)
      (let* ((final-dtype (cond ((and out dtype (not (eq (vt-dtype out) dtype)))
                                 (error "vt-mean: :out 与 :dtype 冲突"))
                                (out (vt-dtype out)) (dtype dtype)
                                (t (if (eq (vt-dtype tensor) :float32) :float32 :float64)))))
        (when (= count 0)
          (let ((nan (vt-get-nan final-dtype))
                (out-shape (if keepdims
                               (loop for d in shape for i below rank
                                     collect (if (or (null axes) (member i axes)) 1 d))
                               (loop for d in shape for i below rank
                                     unless (or (null axes) (member i axes)) collect d))))
            (return-from vt-mean
              (if out (progn (vt-map (lambda (x) (declare (ignore x)) nan) out :dtype final-dtype :out out) out)
                  (vt-full out-shape nan :dtype final-dtype)))))
        (let* ((sum-result (vt-sum tensor :axis axes :keepdims keepdims :dtype final-dtype :out out))
               (div (coerce count (if (eq final-dtype :float32) 'single-float 'double-float))))
          (vt-map (lambda (s) (/ s div)) sum-result :dtype final-dtype :out sum-result))))))

(defun vt-var (tensor &key axis keepdims (ddof 0) dtype out)
  (let* ((shape (vt-shape tensor)) (rank (length shape)))
    (multiple-value-bind (axes n) (%get-axes-count axis rank shape)
      (let* ((divisor (- n ddof))
             (final-dtype (cond ((and out dtype (not (eq (vt-dtype out) dtype)))
                                 (error "vt-var: :out 与 :dtype 冲突"))
                                (out (vt-dtype out)) (dtype dtype)
                                (t (if (eq (vt-dtype tensor) :float32) :float32 :float64)))))
        (if (<= divisor 0)
            (vt-map (lambda (s) (declare (ignore s)) (vt-get-nan final-dtype))
                    (vt-sum tensor :axis axes :keepdims keepdims) :dtype final-dtype :out out)
            (let* ((mean-val (vt-mean tensor :axis axes :keepdims t :dtype final-dtype))
                   (sq-diff (vt-square (vt-- tensor mean-val :dtype final-dtype) :dtype final-dtype))
                   (sum-sq (vt-sum sq-diff :axis axes :keepdims keepdims :dtype final-dtype :out out)))
              (vt-/ sum-sq divisor :dtype final-dtype :out sum-sq)))))))

(defun vt-std (tensor &key axis keepdims (ddof 0) dtype out)
  (let* ((final-dtype (cond ((and out dtype (not (eq (vt-dtype out) dtype)))
                             (error "vt-std: :out 与 :dtype 冲突"))
                            (out (vt-dtype out)) (dtype dtype)
                            (t (if (eq (vt-dtype tensor) :float32) :float32 :float64)))))
    (let ((variance (vt-var tensor :axis axis :keepdims keepdims :ddof ddof :dtype final-dtype :out out)))
      (vt-sqrt variance :dtype final-dtype :out variance))))

;;; ------------------------------------------------------------------
;;; 累积
;;; ------------------------------------------------------------------

(defun vt-cumulative (tensor op init-val &key axis dtype out)
  (let* ((shape (vt-shape tensor)) (rank (length shape))
         (final-dtype (cond ((and out dtype (not (eq (vt-dtype out) dtype)))
                             (error "类型冲突: :out (~a) vs :dtype (~a)" (vt-dtype out) dtype))
                            (dtype dtype) (out (vt-dtype out)) (t (vt-dtype tensor))))
         (lisp-type (vt-dtype->lisp-type final-dtype))
         (result (or out (vt-zeros shape :dtype final-dtype)))
         (in-data (vt-data tensor)) (out-data (vt-data result))
         (in-strides (vt-strides tensor)) (in-offset (vt-offset tensor))
         (out-strides (vt-strides result)) (out-offset (vt-offset result)))
    (if axis
        (let* ((ax (vt-normalize-axis axis rank)) (ax-dim (nth ax shape))
               (indices (make-array rank :element-type '(signed-byte 64) :initial-element 0)))
          (labels ((advance ()
                     (loop for d from (1- rank) downto 0
                           when (/= d ax)
                             do (incf (aref indices d))
                                (if (< (aref indices d) (nth d shape))
                                    (return-from advance t)
                                    (setf (aref indices d) 0)))))
            (loop
              (let ((in-ptr in-offset) (out-ptr out-offset))
                (loop for d from 0 below rank do
                  (incf in-ptr (* (aref indices d) (nth d in-strides)))
                  (incf out-ptr (* (aref indices d) (nth d out-strides))))
                (let ((in-stride (nth ax in-strides)) (out-stride (nth ax out-strides))
                      (cum (coerce init-val lisp-type)))
                  (loop for i from 0 below ax-dim do
                    (setf cum (funcall op cum (aref in-data (+ in-ptr (* i in-stride)))))
                    (setf (aref out-data (+ out-ptr (* i out-stride))) (vt-cast cum final-dtype)))))
              (unless (advance) (return)))))
        (let* ((flat (vt-ravel tensor)) (flat-in (vt-data flat))
               (flat-offset (vt-offset flat)) (cum (coerce init-val lisp-type))
               (out-shape-vec (coerce (vt-shape result) 'simple-vector))
               (out-strs-vec (coerce out-strides 'simple-vector))
               (out-rank (length out-shape-vec)))
          (labels ((recurse (depth out-ptr flat-idx)
                     (if (= depth out-rank)
                         (progn (setf cum (funcall op cum (aref flat-in (+ flat-offset flat-idx))))
                                (setf (aref out-data out-ptr) (vt-cast cum final-dtype))
                                (1+ flat-idx))
                         (let ((dim (svref out-shape-vec depth)) (stride (svref out-strs-vec depth)))
                           (loop for i from 0 below dim
                                 for cur = out-ptr then (+ cur stride)
                                 do (setf flat-idx (recurse (1+ depth) cur flat-idx)))))))
            (recurse 0 out-offset 0))))
    result))

(defun vt-cumsum (tensor &key axis dtype out) (vt-cumulative tensor #'+ 0 :axis axis :dtype dtype :out out))
(defun vt-cumprod (tensor &key axis dtype out) (vt-cumulative tensor #'* 1 :axis axis :dtype dtype :out out))

;;; ------------------------------------------------------------------
;;; 中位数 / 百分位 / 直方图
;;; ------------------------------------------------------------------

(defun vt-median (tensor &key axis)
  (if axis
      (let* ((shape (vt-shape tensor)) (rank (length shape)) (ax (vt-normalize-axis axis rank))
             (out-shape (loop for d in shape for i from 0 unless (= i ax) collect d))
             (result (vt-zeros out-shape :dtype :float64)) (out-strides (vt-strides result)))
        (vt-do-each (ptr val result)
          (declare (ignore val))
          (let ((out-idx (vt-unravel-index ptr out-shape out-strides)))
            (let* ((specs (loop for i from 0 below rank
                                if (= i ax) collect '(:all)
                                  else collect (list (pop out-idx))))
                   (fiber (apply #'vt-slice tensor specs)) (fs (vt-size fiber)))
              (setf (aref (vt-data result) ptr)
                    (if (zerop fs) (vt-get-nan :float64)
                        (let ((vals (loop for i below fs collect (vt-ref fiber i))))
                          (if (some #'vt-float-nan-p vals) (vt-get-nan :float64)
                              (let ((sv (vt-numpy-sort vals #'<)))
                                (if (oddp fs) (vt-cast (nth (floor fs 2) sv) :float64)
                                    (/ (+ (vt-cast (nth (1- (floor fs 2)) sv) :float64)
                                          (vt-cast (nth (floor fs 2) sv) :float64))
                                       2.0d0))))))))))
        result)
      (let* ((flat (vt-flatten tensor)) (size (vt-size flat)))
        (if (zerop size) (make-vt nil (vt-get-nan :float64) :dtype :float64)
            (let ((vals (loop for i below size collect (aref (vt-data flat) i))))
              (if (some #'vt-float-nan-p vals) (make-vt nil (vt-get-nan :float64) :dtype :float64)
                  (let ((sv (vt-numpy-sort vals #'<)))
                    (if (oddp size) (make-vt nil (vt-cast (nth (floor size 2) sv) :float64) :dtype :float64)
                        (make-vt nil (/ (+ (vt-cast (nth (1- (floor size 2)) sv) :float64)
                                           (vt-cast (nth (floor size 2) sv) :float64)) 2.0d0)
                                 :dtype :float64)))))))))

(defun %percent-from-sorted (sorted q interpolation)
  (let* ((n (length sorted)) (idx (* q (1- n)))
         (lower (floor idx)) (upper (min (ceiling idx) (1- n))) (frac (- idx lower)))
    (case interpolation
      (:linear (if (= lower upper) (vt-cast (nth lower sorted) :float64)
                   (+ (* (- 1 frac) (vt-cast (nth lower sorted) :float64))
                      (* frac (vt-cast (nth upper sorted) :float64)))))
      (:lower (vt-cast (nth lower sorted) :float64))
      (:higher (vt-cast (nth upper sorted) :float64))
      (:midpoint (/ (+ (vt-cast (nth lower sorted) :float64) (vt-cast (nth upper sorted) :float64)) 2.0d0))
      (:nearest (vt-cast (nth (if (<= frac 0.5d0) lower upper) sorted) :float64)))))

(defun vt-percentile (tensor percentile &key axis (interpolation :linear))
  (let ((q (/ percentile 100.0d0)))
    (if axis
        (let* ((shape (vt-shape tensor)) (rank (length shape)) (ax (vt-normalize-axis axis rank))
               (out-shape (loop for d in shape for i from 0 unless (= i ax) collect d))
               (result (vt-zeros out-shape :dtype :float64)) (out-strides (vt-strides result)))
          (vt-do-each (ptr val result)
            (declare (ignore val))
            (let ((out-idx (vt-unravel-index ptr out-shape out-strides)))
              (let* ((specs (loop for i from 0 below rank
                                  if (= i ax) collect '(:all)
                                    else collect (list (pop out-idx))))
                     (fiber (apply #'vt-slice tensor specs)) (fs (vt-size fiber)))
                (setf (aref (vt-data result) ptr)
                      (if (zerop fs) (vt-get-nan :float64)
                          (let ((raw (loop for i below fs collect (vt-ref fiber i))))
                            (if (some #'vt-float-nan-p raw) (vt-get-nan :float64)
                                (%percent-from-sorted (vt-numpy-sort raw #'<) q interpolation))))))))
          result)
        (let* ((flat (vt-flatten tensor)) (size (vt-size flat)))
          (if (zerop size) (make-vt nil (vt-get-nan :float64) :dtype :float64)
              (let ((raw (loop for i below size collect (aref (vt-data flat) i))))
                (if (some #'vt-float-nan-p raw) (make-vt nil (vt-get-nan :float64) :dtype :float64)
                    (make-vt nil (%percent-from-sorted (vt-numpy-sort raw #'<) q interpolation) :dtype :float64))))))))

(defun vt-quantile (tensor q &key axis (interpolation :linear))
  (vt-percentile tensor (* q 100) :axis axis :interpolation interpolation))

(defun vt-ptp (tensor &key axis)
  (if axis (vt-- (vt-amax tensor :axis axis) (vt-amin tensor :axis axis))
      (- (vt-item (vt-amax tensor)) (vt-item (vt-amin tensor)))))

(defun vt-histogram (tensor &key bins range density)
  (with-float-safe
    (let* ((flat (vt-flatten tensor)) (data (vt-data flat)) (size (vt-size flat))
           (bins (or bins 10)) (data-min nil) (data-max nil))
      (if range (setf data-min (first range) data-max (second range))
          (progn (unless (= (vt-item (vt-all (vt-isfinite tensor))) 1.0d0)
                   (error "自动确定 bin 范围需要有限输入"))
                 (setf data-min (vt-item (vt-amin tensor)) data-max (vt-item (vt-amax tensor)))))
      (when (= data-min data-max) (setf data-min (- data-min 0.5) data-max (+ data-max 0.5)))
      (let* ((bin-width (/ (- data-max data-min) bins))
             (hist (make-array bins :initial-element 0))
             (edges (make-array (1+ bins) :element-type t)))
        (loop for i from 0 to bins do (setf (aref edges i) (+ data-min (* i bin-width))))
        (loop for i from 0 below size for val = (aref data i)
              when (and (>= val data-min) (<= val data-max))
                do (let ((bi (if (= val data-max) (1- bins) (floor (- val data-min) bin-width))))
                     (incf (aref hist bi))))
        (when density
          (let ((total (reduce #'+ hist)))
            (if (zerop total)
                (loop for i from 0 below bins do (setf (aref hist i) 0.0d0))
                (loop for i from 0 below bins do (setf (aref hist i) (/ (aref hist i) (* total bin-width)))))))
        (values (vt-from-sequence hist :dtype :float64) (vt-from-sequence edges :dtype :float64))))))

;;; ------------------------------------------------------------------
;;; 排序
;;; ------------------------------------------------------------------

(defun vt-sort (tensor &key (axis -1))
  (if axis
      (let* ((shape (vt-shape tensor)) (rank (length shape)) (ax (vt-normalize-axis axis rank))
             (ax-dim (nth ax shape)) (in-strides (vt-strides tensor))
             (in-offset (vt-offset tensor)) (in-data (vt-data tensor))
             (result (vt-copy tensor)) (out-strides (vt-strides result)) (out-data (vt-data result)))
        (labels ((recurse (depth in-ptr out-ptr)
                   (cond ((= depth ax)
                          (let* ((in-stride (nth ax in-strides)) (out-stride (nth ax out-strides))
                                 (vals (loop for i from 0 below ax-dim
                                             for off = (+ in-ptr (* i in-stride))
                                             collect (aref in-data off)))
                                 (sv (vt-numpy-sort vals #'<)))
                            (loop for val in sv for off = out-ptr then (+ off out-stride)
                                  do (setf (aref out-data off) val))))
                         ((< depth rank)
                          (let ((dim (nth depth shape)) (in-stride (nth depth in-strides))
                                (out-stride (nth depth out-strides)))
                            (loop for i from 0 below dim do
                              (recurse (1+ depth) (+ in-ptr (* i in-stride)) (+ out-ptr (* i out-stride))))))
                         (t nil))))
          (recurse 0 in-offset 0))
        result)
      (let* ((flat (vt-flatten tensor))
             (data (coerce (vt-data flat) 'list)))
        (vt-from-sequence (vt-numpy-sort data #'<) :dtype (vt-dtype tensor)))))

(defun vt-argsort (tensor &key (axis -1))
  (if (null axis)
      (let* ((flat (vt-ravel tensor)) (n (vt-size flat)) (in-data (vt-data flat))
             (pairs (loop for i from 0 below n collect (cons (aref in-data i) i)))
             (non-nans '()) (nans '()))
        (dolist (p pairs) (if (vt-float-nan-p (car p)) (push p nans) (push p non-nans)))
        (setf non-nans (stable-sort (nreverse non-nans) #'< :key #'car)
              nans (nreverse nans))
        (%make-vt :data (make-array n :element-type '(signed-byte 64)
                                      :initial-contents (mapcar #'cdr (append non-nans nans)))
                  :shape (list n) :strides '(1) :offset 0 :dtype :int64))
      (let* ((shape (vt-shape tensor)) (rank (length shape)) (ax (vt-normalize-axis axis rank))
             (ax-dim (nth ax shape)) (in-strides (vt-strides tensor))
             (in-offset (vt-offset tensor)) (in-data (vt-data tensor))
             (result (vt-zeros shape :dtype :int64)) (out-strides (vt-strides result))
             (out-data (vt-data result)))
        (labels ((recurse (depth in-ptr out-ptr)
                   (cond ((< depth ax)
                          (let ((dim (nth depth shape)) (in-stride (nth depth in-strides))
                                (out-stride (nth depth out-strides)))
                            (dotimes (i dim)
                              (recurse (1+ depth) (+ in-ptr (* i in-stride)) (+ out-ptr (* i out-stride))))))
                         ((= depth ax)
                          (let* ((in-stride (nth ax in-strides)) (out-stride (nth ax out-strides))
                                 (tail-dims (subseq shape (1+ ax)))
                                 (tail-size (reduce #'* tail-dims :initial-value 1))
                                 (tail-in-strides (subseq in-strides (1+ ax)))
                                 (tail-out-strides (subseq out-strides (1+ ax))))
                            (dotimes (tail-i tail-size)
                              (let ((extra-in 0) (extra-out 0) (rem tail-i))
                                (loop for idx from (1- (length tail-dims)) downto 0
                                      for dim = (nth idx tail-dims)
                                      for is = (nth idx tail-in-strides)
                                      for os = (nth idx tail-out-strides)
                                      do (multiple-value-bind (q r) (floor rem dim)
                                           (incf extra-in (* r is)) (incf extra-out (* r os)) (setf rem q)))
                                (let ((pairs (loop for pos from 0 below ax-dim
                                                   for off = (+ in-ptr (* pos in-stride) extra-in)
                                                   collect (cons (aref in-data off) pos)))
                                      (non-nans '()) (nans '()))
                                  (dolist (p pairs) (if (vt-float-nan-p (car p)) (push p nans) (push p non-nans)))
                                  (setf non-nans (stable-sort (nreverse non-nans) #'< :key #'car)
                                        nans (nreverse nans))
                                  (loop for (val . pos) in (append non-nans nans)
                                        for off = out-ptr then (+ off out-stride)
                                        do (setf (aref out-data (+ off extra-out)) pos)))))))
                         (t nil))))
          (recurse 0 in-offset 0))
        result)))

;;; ------------------------------------------------------------------
;;; nan 感知统计
;;; ------------------------------------------------------------------

(defun vt-nansum (tensor &key axis keepdims dtype out)
  (let* ((mask (vt-isnan tensor)) (clean (vt-where mask 0.0d0 tensor)))
    (vt-sum clean :axis axis :keepdims keepdims :dtype dtype :out out)))

(defun vt-nanmean (tensor &key axis keepdims dtype out)
  (let* ((mask (vt-isnan tensor)) (not-nan (vt-logical-not mask))
         (clean (vt-where mask 0.0d0 tensor))
         (count (vt-sum not-nan :axis axis :keepdims keepdims :dtype :int64))
         (final-dtype (cond ((and out dtype (not (eq (vt-dtype out) dtype))) (error "vt-nanmean: :out 与 :dtype 冲突"))
                            (out (vt-dtype out)) (dtype dtype)
                            (t (if (eq (vt-dtype tensor) :float32) :float32 :float64))))
         (nan (vt-get-nan final-dtype))
         (sum (vt-sum clean :axis axis :keepdims keepdims :dtype final-dtype :out out)))
    (vt-map (lambda (s c) (if (zerop c) nan (/ s c))) sum count :dtype final-dtype :out sum)))

(defun vt-nanvar (tensor &key axis keepdims (ddof 0) dtype out)
  (let* ((mask (vt-isnan tensor)) (not-nan (vt-logical-not mask))
         (final-dtype (cond ((and out dtype (not (eq (vt-dtype out) dtype))) (error "vt-nanvar: :out 与 :dtype 冲突"))
                            (out (vt-dtype out)) (dtype dtype)
                            (t (if (eq (vt-dtype tensor) :float32) :float32 :float64))))
         (nan (vt-get-nan final-dtype)) (zero (if (eq final-dtype :float32) 0.0s0 0.0d0))
         (clean (vt-where mask zero tensor))
         (count (vt-sum not-nan :axis axis :keepdims keepdims :dtype :int64))
         (mean (vt-nanmean tensor :axis axis :keepdims t :dtype final-dtype))
         (sq-diff (vt-* (vt-map (lambda (c m) (* (- c m) (- c m))) clean mean :dtype final-dtype)
                        not-nan :dtype final-dtype))
         (sum2 (vt-sum sq-diff :axis axis :keepdims keepdims :dtype final-dtype :out out))
         (divisor (vt-map (lambda (c) (max 0 (- c ddof))) count :dtype :int64)))
    (vt-map (lambda (s d) (if (<= d 0) nan (/ s d))) sum2 divisor :dtype final-dtype :out sum2)))

(defun vt-nanstd (tensor &key axis keepdims (ddof 0) dtype out)
  (let* ((final-dtype (cond ((and out dtype (not (eq (vt-dtype out) dtype))) (error "vt-nanstd: :out 与 :dtype 冲突"))
                            (out (vt-dtype out)) (dtype dtype)
                            (t (if (eq (vt-dtype tensor) :float32) :float32 :float64))))
         (var (vt-nanvar tensor :axis axis :keepdims keepdims :ddof ddof :dtype final-dtype :out out)))
    (vt-sqrt var :dtype final-dtype :out var)))

(defun vt-nanmax (tensor &key axis keepdims dtype out)
  (if (member (vt-dtype tensor) '(:int32 :int64))
      (vt-amax tensor :axis axis :keepdims keepdims :dtype dtype :out out)
      (let* ((dt (cond ((and out dtype (not (eq (vt-dtype out) dtype))) (error "vt-nanmax: :out 与 :dtype 冲突"))
                       (out (vt-dtype out)) (dtype dtype) (t (vt-dtype tensor))))
             (mask (vt-isnan tensor))
             (clean (vt-where mask (vt-get-neg-inf dt) tensor :dtype dt))
             (result (vt-amax clean :axis axis :keepdims keepdims :dtype dt :out out)))
        (vt-where (vt-all mask :axis axis :keepdims keepdims) (vt-get-nan dt) result :dtype dt :out result))))

(defun vt-nanmin (tensor &key axis keepdims dtype out)
  (if (member (vt-dtype tensor) '(:int32 :int64))
      (vt-amin tensor :axis axis :keepdims keepdims :dtype dtype :out out)
      (let* ((dt (cond ((and out dtype (not (eq (vt-dtype out) dtype))) (error "vt-nanmin: :out 与 :dtype 冲突"))
                       (out (vt-dtype out)) (dtype dtype) (t (vt-dtype tensor))))
             (mask (vt-isnan tensor))
             (clean (vt-where mask (vt-get-pos-inf dt) tensor :dtype dt))
             (result (vt-amin clean :axis axis :keepdims keepdims :dtype dt :out out)))
        (vt-where (vt-all mask :axis axis :keepdims keepdims) (vt-get-nan dt) result :dtype dt :out result))))

(defun vt-nanargmax (tensor &key axis out)
  (if (member (vt-dtype tensor) '(:int32 :int64))
      (vt-argmax tensor :axis axis :out out)
      (vt-argmax (vt-where (vt-isnan tensor) (vt-get-neg-inf (vt-dtype tensor)) tensor) :axis axis :out out)))

(defun vt-nanargmin (tensor &key axis out)
  (if (member (vt-dtype tensor) '(:int32 :int64))
      (vt-argmin tensor :axis axis :out out)
      (vt-argmin (vt-where (vt-isnan tensor) (vt-get-pos-inf (vt-dtype tensor)) tensor) :axis axis :out out)))

(defun vt-nanprod (tensor &key axis keepdims dtype out)
  (if (member (vt-dtype tensor) '(:int32 :int64))
      (vt-prod tensor :axis axis :keepdims keepdims :dtype dtype :out out)
      (vt-prod (vt-where (vt-isnan tensor) 1.0d0 tensor) :axis axis :keepdims keepdims :dtype dtype :out out)))

(defun vt-nanmedian (tensor &key axis keepdims out)
  (if (member (vt-dtype tensor) '(:int32 :int64))
      (vt-median tensor :axis axis)
      (let* ((nan (vt-get-nan :float64)) (in-data (vt-data tensor))
             (in-strides (vt-strides tensor)) (in-offset (vt-offset tensor))
             (in-shape (vt-shape tensor)) (rank (length in-shape)))
        (if (null axis)
            (let ((vals '()))
              (vt-do-each (ptr val tensor)
                (declare (ignore ptr))
                (unless (vt-float-nan-p val) (push val vals)))
              (setf vals (sort vals #'<))
              (let ((result (cond ((null vals) nan)
                                  ((oddp (length vals)) (coerce (nth (floor (length vals) 2) vals) 'double-float))
                                  (t (/ (+ (nth (1- (/ (length vals) 2)) vals) (nth (/ (length vals) 2) vals)) 2.0d0)))))
                (if out (progn (vt-fill out result) out) (make-vt nil result :dtype :float64))))
            (let* ((ax (vt-normalize-axis axis rank)) (ax-size (nth ax in-shape))
                   (ax-stride (nth ax in-strides))
                   (out-shape (if keepdims
                                  (loop for d in in-shape for i from 0 collect (if (= i ax) 1 d))
                                  (loop for d in in-shape for i from 0 unless (= i ax) collect d)))
                   (res (vt-zeros out-shape :dtype :float64))
                   (res-data (vt-data res)) (res-offset (vt-offset res))
                   (out-rank (length out-shape))
                   (out-dims (coerce out-shape 'simple-vector))
                   (out-strs (coerce (vt-strides res) 'simple-vector))
                   (in-map (let ((m (make-array out-rank :element-type 'fixnum)) (k 0))
                             (loop for i from 0 below rank unless (= i ax)
                                   do (setf (aref m k) i) (incf k))
                             m))
                   (in-strs (coerce (loop for i below out-rank collect (nth (aref in-map i) in-strides))
                                    'simple-vector)))
              (labels ((compute (depth in-ptr out-ptr)
                         (if (= depth out-rank)
                             (let ((vals '()))
                               (loop for i from 0 below ax-size
                                     for ptr = in-ptr then (+ ptr ax-stride)
                                     for v = (aref in-data ptr)
                                     unless (vt-float-nan-p v) do (push (coerce v 'double-float) vals))
                               (setf vals (nreverse vals))
                               (setf (aref res-data out-ptr)
                                     (cond ((null vals) nan)
                                           ((oddp (length vals)) (nth (floor (length vals) 2) vals))
                                           (t (/ (+ (nth (1- (/ (length vals) 2)) vals) (nth (/ (length vals) 2) vals)) 2.0d0)))))
                             (let ((dim (svref out-dims depth)) (out-str (svref out-strs depth))
                                   (in-str (svref in-strs depth)))
                               (loop for i from 0 below dim do
                                 (compute (1+ depth) in-ptr out-ptr)
                                 (incf in-ptr in-str) (incf out-ptr out-str))))))
                (compute 0 in-offset res-offset))
              (if out (progn (vt-copy-into out res) out) res))))))

;;; ------------------------------------------------------------------
;;; 差分 / 积分 / 相关 / 卷积 / 插值 / 梯度
;;; ------------------------------------------------------------------

(defun vt-diff (vt &key (axis -1) (n 1))
  (let ((result vt))
    (loop repeat n do
      (let* ((sh (vt-shape result)) (ax (vt-normalize-axis axis (length sh))) (len (nth ax sh)))
        (when (< len 2)
          (return-from vt-diff (vt-zeros (append (subseq sh 0 ax) '(0) (subseq sh (1+ ax)))
                                         :dtype (vt-dtype result))))
        (setf result (vt-- (vt-narrow result ax 1 len) (vt-narrow result ax 0 (1- len)))))
      finally (return result))))

(defun vt-trapz (y &key (x nil) (dx 1.0d0) (axis -1))
  (let* ((sh (vt-shape y)) (ax (vt-normalize-axis axis (length sh))) (n (nth ax sh)))
    (when (< n 2)
      (return-from vt-trapz (vt-zeros (append (subseq sh 0 ax) (subseq sh (1+ ax))) :dtype (vt-dtype y))))
    (let ((h (if x (vt-diff (ensure-vt x)) (make-vt (list (1- n)) dx :dtype (vt-dtype y)))))
      (setf h (vt-reshape h (append (make-list ax :initial-element 1) (list (1- n))
                                    (make-list (- (length sh) ax 1) :initial-element 1))))
      (let* ((left (vt-narrow y ax 0 (1- n))) (right (vt-narrow y ax 1 n))
             (integrand (vt-map (lambda (l r hh) (* 0.5d0 (+ l r) hh)) left right h)))
        (vt-sum integrand :axis ax)))))

(defun vt-correlate (a v &key (mode :full))
  (let* ((a-flat (vt-contiguous (vt-flatten a))) (v-flat (vt-contiguous (vt-flatten v)))
         (n (vt-size a-flat)) (m (vt-size v-flat))
         (a-data (vt-data a-flat)) (v-data (vt-data v-flat)))
    (flet ((compute (k)
             (let ((sum 0.0d0))
               (loop for j from (max 0 (- k)) below (min m (- n k))
                     do (incf sum (* (aref a-data (+ j k)) (aref v-data j))))
               sum)))
      (let* ((full-len (+ n m -1)) (offset (1- m))
             (full (make-array full-len :element-type 'double-float)))
        (loop for k from (- offset) below n for i from 0
              do (setf (aref full i) (compute k)))
        (ecase mode
          (:full (%make-vt :data full :shape (list full-len) :strides '(1) :offset 0 :dtype :float64))
          (:valid (let* ((len (max 0 (1+ (- n m)))) (start offset)
                         (data (make-array len :element-type 'double-float)))
                    (loop for i from 0 below len do (setf (aref data i) (aref full (+ start i))))
                    (%make-vt :data data :shape (list len) :strides '(1) :offset 0 :dtype :float64)))
          (:same (let* ((out-len (max n m)) (start (floor (- full-len out-len) 2))
                        (data (make-array out-len :element-type 'double-float)))
                   (loop for i from 0 below out-len do (setf (aref data i) (aref full (+ start i))))
                   (%make-vt :data data :shape (list out-len) :strides '(1) :offset 0 :dtype :float64))))))))

(defun vt-convolve (a v &key (mode :full))
  (vt-correlate (vt-contiguous a) (vt-contiguous (vt-flip v)) :mode mode))

(defun vt-interp (x xp fp &key (left nil) (right nil))
  (let* ((xp-vt (if (eq (vt-dtype xp) :float64) xp (vt-astype xp :float64)))
         (fp-vt (if (eq (vt-dtype fp) :float64) fp (vt-astype fp :float64)))
         (x-vt (ensure-vt x :dtype :float64))
         (xp-data (vt-data xp-vt)) (fp-data (vt-data fp-vt)) (n (vt-size xp-vt))
         (x-data (vt-data x-vt)) (x-size (vt-size x-vt))
         (out (vt-zeros (vt-shape x-vt) :dtype :float64)) (out-data (vt-data out))
         (xp0 (aref xp-data 0)) (fp0 (aref fp-data 0))
         (xp-end (aref xp-data (1- n))) (fp-end (aref fp-data (1- n)))
         (left-val (if left (vt-cast left :float64) fp0))
         (right-val (if right (vt-cast right :float64) fp-end)))
    (loop for i from 0 below x-size for xi = (aref x-data i) do
      (setf (aref out-data i)
            (cond ((<= xi xp0) left-val) ((>= xi xp-end) right-val)
                  (t (let ((lo 0) (hi (- n 2)))
                       (loop while (< lo hi) do
                         (let ((mid (ash (+ lo hi 1) -1)))
                           (if (<= (aref xp-data mid) xi) (setf lo mid) (setf hi (1- mid)))))
                       (let* ((xl (aref xp-data lo)) (xr (aref xp-data (1+ lo)))
                              (yl (aref fp-data lo)) (yr (aref fp-data (1+ lo)))
                              (denom (- xr xl)))
                         (if (zerop denom) yl (+ yl (* (- yr yl) (/ (- xi xl) denom))))))))))
    out))

(defun vt-gradient (tensor &key (spacing 1.0d0) axis)
  (let* ((shape (vt-shape tensor)) (rank (length shape))
         (axes (cond ((null axis) (loop for i below rank collect i))
                     ((integerp axis) (list (vt-normalize-axis axis rank)))
                     ((listp axis) (mapcar (lambda (a) (vt-normalize-axis a rank)) axis))
                     (t (error "axis 必须是 nil、整数或整数列表"))))
         (spacings (cond ((numberp spacing) (make-list (length axes) :initial-element spacing))
                         ((listp spacing) spacing)
                         ((vt-p spacing) (list spacing))
                         (t (error "spacing 必须是数字、列表或 1d 张量")))))
    (labels ((slice-specs (ax s e)
               (loop for d from 0 below rank collect (if (= d ax) (list s e) '(:all))))
             (grad-along (ax sp)
               (let ((n (nth ax shape)))
                 (when (< n 2) (error "轴 ~a 长度 ~a 太小" ax n))
                 (if (numberp sp)
                     (if (= n 2)
                         (let ((edge (vt-/ (vt-- (apply #'vt-slice tensor (slice-specs ax 1 2))
                                                 (apply #'vt-slice tensor (slice-specs ax 0 1))) sp)))
                           (vt-concatenate ax edge edge))
                         (let ((left (vt-/ (vt-- (apply #'vt-slice tensor (slice-specs ax 1 2))
                                                 (apply #'vt-slice tensor (slice-specs ax 0 1))) sp))
                               (inner (vt-/ (vt-- (apply #'vt-slice tensor (slice-specs ax 2 n))
                                                  (apply #'vt-slice tensor (slice-specs ax 0 (- n 2)))) (* 2.0d0 sp)))
                               (right (vt-/ (vt-- (apply #'vt-slice tensor (slice-specs ax (1- n) n))
                                                  (apply #'vt-slice tensor (slice-specs ax (- n 2) (1- n)))) sp)))
                           (vt-concatenate ax left inner right)))
                     (let* ((h (ensure-vt sp)) (nh (vt-size h)))
                       (assert (= n nh) (sp) "spacing 数组长度必须与轴一致")
                       (if (= n 2)
                           (let* ((hd (vt-- (vt-slice h '(1 2)) (vt-slice h '(0 1))))
                                  (df (vt-- (apply #'vt-slice tensor (slice-specs ax 1 2))
                                            (apply #'vt-slice tensor (slice-specs ax 0 1))))
                                  (g (vt-/ df hd)))
                             (vt-concatenate ax g g))
                           (let ((hl (vt-- (vt-slice h '(1 2)) (vt-slice h '(0 1))))
                                 (hr (vt-- (vt-slice h (list (1- n) n)) (vt-slice h (list (- n 2) (1- n)))))
                                 (hi (vt-- (vt-slice h (list 2 n)) (vt-slice h (list 0 (- n 2)))))
                                 (dl (vt-- (apply #'vt-slice tensor (slice-specs ax 1 2))
                                           (apply #'vt-slice tensor (slice-specs ax 0 1))))
                                 (dr (vt-- (apply #'vt-slice tensor (slice-specs ax (1- n) n))
                                           (apply #'vt-slice tensor (slice-specs ax (- n 2) (1- n)))))
                                 (di (vt-- (apply #'vt-slice tensor (slice-specs ax 2 n))
                                           (apply #'vt-slice tensor (slice-specs ax 0 (- n 2))))))
                             (vt-concatenate ax (vt-/ dl hl) (vt-/ di hi) (vt-/ dr hr)))))))))
      (let ((results (loop for ax in axes for sp in spacings collect (grad-along ax sp))))
        (if (and (integerp axis) (null (cdr axes))) (car results) results)))))
